import * as path from 'node:path';
import { defineConfig } from 'orval';

const infiniteOperationNames = [
  "FindBookings",
  "FindClients",
  "FindJobs",
  "FindMasters"
];

export default defineConfig({
  'core-api': {
    input: {
      filters: {
        mode: 'exclude',
        tags: ['Auth'],
      },
      target: './src/state/core-api-spec.yaml',
      validation: false,
    },
    output: {
      mode: 'tags',
      target: './src/state/endpoints/api.ts',
      client: 'react-query',
      tslint: true,
      clean: true,
      override: {
        header: (info): string[] => [
          'Generated by orval',
          'Do not edit manually.',
          ...(info.title ? [info.title] : []),
          ...(info.description ? [info.description] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
          'eslint-disable no-nested-ternary',
        ],
        enumGenerationType: 'enum',
        useTypeOverInterfaces: true,
        useDates: true,
        query: {
          useQuery: true,
          useSuspenseQuery: true,
          usePrefetch: false,
        },
        operations: infiniteOperationNames.reduce((acc, operation) => {
          acc[operation] = {
            query: {
              useQuery: true,
              useSuspenseQuery: true,
              useInfinite: true,
              useSuspenseInfiniteQuery: false,
              useInfiniteQueryParam: 'page',
            },
          };
          return acc;
        }, {}),
        mutator: {
          path: './src/state/mutator/custom-client.ts',
          name: 'customClient',
          alias: {
            '@beautify-baltics-apps/api-client': path.resolve(
              __dirname,
              '../../packages/api-client/src/index.ts',
            ),
          },
        },
        contentType: {
          include: ['multipart/form-data', 'application/json', 'application/xml'],
        },
      },
    },
    hooks: {
      afterAllFilesWrite: 'npx nx run back-office:lint-state',
    },
  },
});
