/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as TreatmentsIndexRouteRouteImport } from './routes/treatments/index.route'
import { Route as RegisterIndexRouteRouteImport } from './routes/register/index.route'
import { Route as MasterIndexRouteRouteImport } from './routes/master/index.route'
import { Route as LoginIndexRouteRouteImport } from './routes/login/index.route'
import { Route as HomeIndexRouteRouteImport } from './routes/home/index.route'
import { Route as ExploreIndexRouteRouteImport } from './routes/explore/index.route'
import { Route as DashboardIndexRouteRouteImport } from './routes/dashboard/index.route'
import { Route as MastersMasterIdIndexRouteRouteImport } from './routes/masters/$masterId/index.route'
import { Route as MasterTimeSlotsIndexRouteRouteImport } from './routes/master/time-slots/index.route'
import { Route as MasterSettingsIndexRouteRouteImport } from './routes/master/settings/index.route'
import { Route as MasterServicesIndexRouteRouteImport } from './routes/master/services/index.route'
import { Route as MasterEarningsIndexRouteRouteImport } from './routes/master/earnings/index.route'
import { Route as MasterBookingsIndexRouteRouteImport } from './routes/master/bookings/index.route'
import { Route as ClientExploreIndexRouteRouteImport } from './routes/client/explore/index.route'
import { Route as ClientBookingsIndexRouteRouteImport } from './routes/client/bookings/index.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRouteRoute = TreatmentsIndexRouteRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRouteRoute = RegisterIndexRouteRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterIndexRouteRoute = MasterIndexRouteRouteImport.update({
  id: '/master/',
  path: '/master/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRouteRoute = LoginIndexRouteRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRouteRoute = HomeIndexRouteRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRouteRoute = ExploreIndexRouteRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRouteRoute = DashboardIndexRouteRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersMasterIdIndexRouteRoute =
  MastersMasterIdIndexRouteRouteImport.update({
    id: '/masters/$masterId/',
    path: '/masters/$masterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterTimeSlotsIndexRouteRoute =
  MasterTimeSlotsIndexRouteRouteImport.update({
    id: '/master/time-slots/',
    path: '/master/time-slots/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterSettingsIndexRouteRoute =
  MasterSettingsIndexRouteRouteImport.update({
    id: '/master/settings/',
    path: '/master/settings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterServicesIndexRouteRoute =
  MasterServicesIndexRouteRouteImport.update({
    id: '/master/services/',
    path: '/master/services/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterEarningsIndexRouteRoute =
  MasterEarningsIndexRouteRouteImport.update({
    id: '/master/earnings/',
    path: '/master/earnings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MasterBookingsIndexRouteRoute =
  MasterBookingsIndexRouteRouteImport.update({
    id: '/master/bookings/',
    path: '/master/bookings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientExploreIndexRouteRoute = ClientExploreIndexRouteRouteImport.update({
  id: '/client/explore/',
  path: '/client/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBookingsIndexRouteRoute =
  ClientBookingsIndexRouteRouteImport.update({
    id: '/client/bookings/',
    path: '/client/bookings/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/dashboard': typeof DashboardIndexRouteRoute
  '/explore': typeof ExploreIndexRouteRoute
  '/home': typeof HomeIndexRouteRoute
  '/login': typeof LoginIndexRouteRoute
  '/master': typeof MasterIndexRouteRoute
  '/register': typeof RegisterIndexRouteRoute
  '/treatments': typeof TreatmentsIndexRouteRoute
  '/client/bookings': typeof ClientBookingsIndexRouteRoute
  '/client/explore': typeof ClientExploreIndexRouteRoute
  '/master/bookings': typeof MasterBookingsIndexRouteRoute
  '/master/earnings': typeof MasterEarningsIndexRouteRoute
  '/master/services': typeof MasterServicesIndexRouteRoute
  '/master/settings': typeof MasterSettingsIndexRouteRoute
  '/master/time-slots': typeof MasterTimeSlotsIndexRouteRoute
  '/masters/$masterId': typeof MastersMasterIdIndexRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/dashboard': typeof DashboardIndexRouteRoute
  '/explore': typeof ExploreIndexRouteRoute
  '/home': typeof HomeIndexRouteRoute
  '/login': typeof LoginIndexRouteRoute
  '/master': typeof MasterIndexRouteRoute
  '/register': typeof RegisterIndexRouteRoute
  '/treatments': typeof TreatmentsIndexRouteRoute
  '/client/bookings': typeof ClientBookingsIndexRouteRoute
  '/client/explore': typeof ClientExploreIndexRouteRoute
  '/master/bookings': typeof MasterBookingsIndexRouteRoute
  '/master/earnings': typeof MasterEarningsIndexRouteRoute
  '/master/services': typeof MasterServicesIndexRouteRoute
  '/master/settings': typeof MasterSettingsIndexRouteRoute
  '/master/time-slots': typeof MasterTimeSlotsIndexRouteRoute
  '/masters/$masterId': typeof MastersMasterIdIndexRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/dashboard/': typeof DashboardIndexRouteRoute
  '/explore/': typeof ExploreIndexRouteRoute
  '/home/': typeof HomeIndexRouteRoute
  '/login/': typeof LoginIndexRouteRoute
  '/master/': typeof MasterIndexRouteRoute
  '/register/': typeof RegisterIndexRouteRoute
  '/treatments/': typeof TreatmentsIndexRouteRoute
  '/client/bookings/': typeof ClientBookingsIndexRouteRoute
  '/client/explore/': typeof ClientExploreIndexRouteRoute
  '/master/bookings/': typeof MasterBookingsIndexRouteRoute
  '/master/earnings/': typeof MasterEarningsIndexRouteRoute
  '/master/services/': typeof MasterServicesIndexRouteRoute
  '/master/settings/': typeof MasterSettingsIndexRouteRoute
  '/master/time-slots/': typeof MasterTimeSlotsIndexRouteRoute
  '/masters/$masterId/': typeof MastersMasterIdIndexRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/home'
    | '/login'
    | '/master'
    | '/register'
    | '/treatments'
    | '/client/bookings'
    | '/client/explore'
    | '/master/bookings'
    | '/master/earnings'
    | '/master/services'
    | '/master/settings'
    | '/master/time-slots'
    | '/masters/$masterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/home'
    | '/login'
    | '/master'
    | '/register'
    | '/treatments'
    | '/client/bookings'
    | '/client/explore'
    | '/master/bookings'
    | '/master/earnings'
    | '/master/services'
    | '/master/settings'
    | '/master/time-slots'
    | '/masters/$masterId'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/explore/'
    | '/home/'
    | '/login/'
    | '/master/'
    | '/register/'
    | '/treatments/'
    | '/client/bookings/'
    | '/client/explore/'
    | '/master/bookings/'
    | '/master/earnings/'
    | '/master/services/'
    | '/master/settings/'
    | '/master/time-slots/'
    | '/masters/$masterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  DashboardIndexRouteRoute: typeof DashboardIndexRouteRoute
  ExploreIndexRouteRoute: typeof ExploreIndexRouteRoute
  HomeIndexRouteRoute: typeof HomeIndexRouteRoute
  LoginIndexRouteRoute: typeof LoginIndexRouteRoute
  MasterIndexRouteRoute: typeof MasterIndexRouteRoute
  RegisterIndexRouteRoute: typeof RegisterIndexRouteRoute
  TreatmentsIndexRouteRoute: typeof TreatmentsIndexRouteRoute
  ClientBookingsIndexRouteRoute: typeof ClientBookingsIndexRouteRoute
  ClientExploreIndexRouteRoute: typeof ClientExploreIndexRouteRoute
  MasterBookingsIndexRouteRoute: typeof MasterBookingsIndexRouteRoute
  MasterEarningsIndexRouteRoute: typeof MasterEarningsIndexRouteRoute
  MasterServicesIndexRouteRoute: typeof MasterServicesIndexRouteRoute
  MasterSettingsIndexRouteRoute: typeof MasterSettingsIndexRouteRoute
  MasterTimeSlotsIndexRouteRoute: typeof MasterTimeSlotsIndexRouteRoute
  MastersMasterIdIndexRouteRoute: typeof MastersMasterIdIndexRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/': {
      id: '/master/'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/$masterId/': {
      id: '/masters/$masterId/'
      path: '/masters/$masterId'
      fullPath: '/masters/$masterId'
      preLoaderRoute: typeof MastersMasterIdIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/time-slots/': {
      id: '/master/time-slots/'
      path: '/master/time-slots'
      fullPath: '/master/time-slots'
      preLoaderRoute: typeof MasterTimeSlotsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/settings/': {
      id: '/master/settings/'
      path: '/master/settings'
      fullPath: '/master/settings'
      preLoaderRoute: typeof MasterSettingsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/services/': {
      id: '/master/services/'
      path: '/master/services'
      fullPath: '/master/services'
      preLoaderRoute: typeof MasterServicesIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/earnings/': {
      id: '/master/earnings/'
      path: '/master/earnings'
      fullPath: '/master/earnings'
      preLoaderRoute: typeof MasterEarningsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/bookings/': {
      id: '/master/bookings/'
      path: '/master/bookings'
      fullPath: '/master/bookings'
      preLoaderRoute: typeof MasterBookingsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/explore/': {
      id: '/client/explore/'
      path: '/client/explore'
      fullPath: '/client/explore'
      preLoaderRoute: typeof ClientExploreIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/bookings/': {
      id: '/client/bookings/'
      path: '/client/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  DashboardIndexRouteRoute: DashboardIndexRouteRoute,
  ExploreIndexRouteRoute: ExploreIndexRouteRoute,
  HomeIndexRouteRoute: HomeIndexRouteRoute,
  LoginIndexRouteRoute: LoginIndexRouteRoute,
  MasterIndexRouteRoute: MasterIndexRouteRoute,
  RegisterIndexRouteRoute: RegisterIndexRouteRoute,
  TreatmentsIndexRouteRoute: TreatmentsIndexRouteRoute,
  ClientBookingsIndexRouteRoute: ClientBookingsIndexRouteRoute,
  ClientExploreIndexRouteRoute: ClientExploreIndexRouteRoute,
  MasterBookingsIndexRouteRoute: MasterBookingsIndexRouteRoute,
  MasterEarningsIndexRouteRoute: MasterEarningsIndexRouteRoute,
  MasterServicesIndexRouteRoute: MasterServicesIndexRouteRoute,
  MasterSettingsIndexRouteRoute: MasterSettingsIndexRouteRoute,
  MasterTimeSlotsIndexRouteRoute: MasterTimeSlotsIndexRouteRoute,
  MastersMasterIdIndexRouteRoute: MastersMasterIdIndexRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
