/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteRouteImport } from './routes/index.route'
import { Route as TreatmentsIndexRouteRouteImport } from './routes/treatments/index.route'
import { Route as RegisterIndexRouteRouteImport } from './routes/register/index.route'
import { Route as LoginIndexRouteRouteImport } from './routes/login/index.route'
import { Route as HomeIndexRouteRouteImport } from './routes/home/index.route'
import { Route as ExploreIndexRouteRouteImport } from './routes/explore/index.route'
import { Route as DashboardIndexRouteRouteImport } from './routes/dashboard/index.route'
import { Route as MasterMasterIdIndexRouteRouteImport } from './routes/master/$masterId/index.route'
import { Route as ClientBookingsIndexRouteRouteImport } from './routes/client/bookings/index.route'

const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRouteRoute = TreatmentsIndexRouteRouteImport.update({
  id: '/treatments/',
  path: '/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRouteRoute = RegisterIndexRouteRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRouteRoute = LoginIndexRouteRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRouteRoute = HomeIndexRouteRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRouteRoute = ExploreIndexRouteRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRouteRoute = DashboardIndexRouteRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterMasterIdIndexRouteRoute =
  MasterMasterIdIndexRouteRouteImport.update({
    id: '/master/$masterId/',
    path: '/master/$masterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientBookingsIndexRouteRoute =
  ClientBookingsIndexRouteRouteImport.update({
    id: '/client/bookings/',
    path: '/client/bookings/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/dashboard': typeof DashboardIndexRouteRoute
  '/explore': typeof ExploreIndexRouteRoute
  '/home': typeof HomeIndexRouteRoute
  '/login': typeof LoginIndexRouteRoute
  '/register': typeof RegisterIndexRouteRoute
  '/treatments': typeof TreatmentsIndexRouteRoute
  '/client/bookings': typeof ClientBookingsIndexRouteRoute
  '/master/$masterId': typeof MasterMasterIdIndexRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/dashboard': typeof DashboardIndexRouteRoute
  '/explore': typeof ExploreIndexRouteRoute
  '/home': typeof HomeIndexRouteRoute
  '/login': typeof LoginIndexRouteRoute
  '/register': typeof RegisterIndexRouteRoute
  '/treatments': typeof TreatmentsIndexRouteRoute
  '/client/bookings': typeof ClientBookingsIndexRouteRoute
  '/master/$masterId': typeof MasterMasterIdIndexRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/dashboard/': typeof DashboardIndexRouteRoute
  '/explore/': typeof ExploreIndexRouteRoute
  '/home/': typeof HomeIndexRouteRoute
  '/login/': typeof LoginIndexRouteRoute
  '/register/': typeof RegisterIndexRouteRoute
  '/treatments/': typeof TreatmentsIndexRouteRoute
  '/client/bookings/': typeof ClientBookingsIndexRouteRoute
  '/master/$masterId/': typeof MasterMasterIdIndexRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/home'
    | '/login'
    | '/register'
    | '/treatments'
    | '/client/bookings'
    | '/master/$masterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/home'
    | '/login'
    | '/register'
    | '/treatments'
    | '/client/bookings'
    | '/master/$masterId'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/explore/'
    | '/home/'
    | '/login/'
    | '/register/'
    | '/treatments/'
    | '/client/bookings/'
    | '/master/$masterId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  DashboardIndexRouteRoute: typeof DashboardIndexRouteRoute
  ExploreIndexRouteRoute: typeof ExploreIndexRouteRoute
  HomeIndexRouteRoute: typeof HomeIndexRouteRoute
  LoginIndexRouteRoute: typeof LoginIndexRouteRoute
  RegisterIndexRouteRoute: typeof RegisterIndexRouteRoute
  TreatmentsIndexRouteRoute: typeof TreatmentsIndexRouteRoute
  ClientBookingsIndexRouteRoute: typeof ClientBookingsIndexRouteRoute
  MasterMasterIdIndexRouteRoute: typeof MasterMasterIdIndexRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/$masterId/': {
      id: '/master/$masterId/'
      path: '/master/$masterId'
      fullPath: '/master/$masterId'
      preLoaderRoute: typeof MasterMasterIdIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/bookings/': {
      id: '/client/bookings/'
      path: '/client/bookings'
      fullPath: '/client/bookings'
      preLoaderRoute: typeof ClientBookingsIndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  DashboardIndexRouteRoute: DashboardIndexRouteRoute,
  ExploreIndexRouteRoute: ExploreIndexRouteRoute,
  HomeIndexRouteRoute: HomeIndexRouteRoute,
  LoginIndexRouteRoute: LoginIndexRouteRoute,
  RegisterIndexRouteRoute: RegisterIndexRouteRoute,
  TreatmentsIndexRouteRoute: TreatmentsIndexRouteRoute,
  ClientBookingsIndexRouteRoute: ClientBookingsIndexRouteRoute,
  MasterMasterIdIndexRouteRoute: MasterMasterIdIndexRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
