/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {
  useMutation,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  CreateJobCategoryRequest,
  CreateJobCategoryResponse,
  CreateJobRequest,
  CreateJobResponse,
  FindUsersParams,
  FindUsersResponsePagedResponse,
  GetBookingStatisticsResponse,
  GetClientStatisticsResponse,
  GetDashboardSummaryResponse,
  GetMasterStatisticsResponse,
  GetServiceStatisticsResponse,
  GetUserStatisticsResponse,
  ProblemDetails,
  SetUserRoleRequest,
  SetUserRoleResponse,
  UpdateJobCategoryRequest,
  UpdateJobCategoryResponse,
  UpdateJobRequest,
  UpdateJobResponse,
  ValidationProblemDetails,
} from './api.schemas';

export const adminCreateJobCategory = (
  createJobCategoryRequest: CreateJobCategoryRequest,
  signal?: AbortSignal,
) => customClient<CreateJobCategoryResponse>(
  {
    url: '/api/v1/admin/job-categories',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createJobCategoryRequest,
    signal,
  },
);

export const getAdminCreateJobCategoryMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJobCategory>>, TError, { data: CreateJobCategoryRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminCreateJobCategory>>, TError, { data: CreateJobCategoryRequest }, TContext> => {
  const mutationKey = ['adminCreateJobCategory'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateJobCategory>>, { data: CreateJobCategoryRequest }> = (props) => {
    const { data } = props ?? {};

    return adminCreateJobCategory(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminCreateJobCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateJobCategory>>>;
export type AdminCreateJobCategoryMutationBody = CreateJobCategoryRequest;
export type AdminCreateJobCategoryMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminCreateJobCategory = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJobCategory>>, TError, { data: CreateJobCategoryRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminCreateJobCategory>>,
  TError,
  { data: CreateJobCategoryRequest },
  TContext
  > => {
  const mutationOptions = getAdminCreateJobCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUpdateJobCategory = (
  id: string,
  updateJobCategoryRequest: UpdateJobCategoryRequest,
) => customClient<UpdateJobCategoryResponse>(
  {
    url: `/api/v1/admin/job-categories/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateJobCategoryRequest,
  },
);

export const getAdminUpdateJobCategoryMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJobCategory>>, TError, { id: string;data: UpdateJobCategoryRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJobCategory>>, TError, { id: string;data: UpdateJobCategoryRequest }, TContext> => {
  const mutationKey = ['adminUpdateJobCategory'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateJobCategory>>, { id: string;data: UpdateJobCategoryRequest }> = (props) => {
    const { id, data } = props ?? {};

    return adminUpdateJobCategory(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUpdateJobCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateJobCategory>>>;
export type AdminUpdateJobCategoryMutationBody = UpdateJobCategoryRequest;
export type AdminUpdateJobCategoryMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminUpdateJobCategory = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJobCategory>>, TError, { id: string;data: UpdateJobCategoryRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminUpdateJobCategory>>,
  TError,
  { id: string;data: UpdateJobCategoryRequest },
  TContext
  > => {
  const mutationOptions = getAdminUpdateJobCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminDeleteJobCategory = (
  id: string,
) => customClient<void>(
  { url: `/api/v1/admin/job-categories/${id}`, method: 'DELETE' },
);

export const getAdminDeleteJobCategoryMutationOptions = <TError = ProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteJobCategory>>, TError, { id: string }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminDeleteJobCategory>>, TError, { id: string }, TContext> => {
  const mutationKey = ['adminDeleteJobCategory'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDeleteJobCategory>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return adminDeleteJobCategory(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminDeleteJobCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof adminDeleteJobCategory>>>;

export type AdminDeleteJobCategoryMutationError = ProblemDetails | ProblemDetails;

export const useAdminDeleteJobCategory = <TError = ProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDeleteJobCategory>>, TError, { id: string }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminDeleteJobCategory>>,
  TError,
  { id: string },
  TContext
  > => {
  const mutationOptions = getAdminDeleteJobCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminCreateJob = (
  createJobRequest: CreateJobRequest,
  signal?: AbortSignal,
) => customClient<CreateJobResponse>(
  {
    url: '/api/v1/admin/jobs',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createJobRequest,
    signal,
  },
);

export const getAdminCreateJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJob>>, TError, { data: CreateJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminCreateJob>>, TError, { data: CreateJobRequest }, TContext> => {
  const mutationKey = ['adminCreateJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateJob>>, { data: CreateJobRequest }> = (props) => {
    const { data } = props ?? {};

    return adminCreateJob(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminCreateJobMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateJob>>>;
export type AdminCreateJobMutationBody = CreateJobRequest;
export type AdminCreateJobMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminCreateJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJob>>, TError, { data: CreateJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminCreateJob>>,
  TError,
  { data: CreateJobRequest },
  TContext
  > => {
  const mutationOptions = getAdminCreateJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUpdateJob = (
  id: string,
  updateJobRequest: UpdateJobRequest,
) => customClient<UpdateJobResponse>(
  {
    url: `/api/v1/admin/jobs/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateJobRequest,
  },
);

export const getAdminUpdateJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext> => {
  const mutationKey = ['adminUpdateJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateJob>>, { id: string;data: UpdateJobRequest }> = (props) => {
    const { id, data } = props ?? {};

    return adminUpdateJob(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUpdateJobMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateJob>>>;
export type AdminUpdateJobMutationBody = UpdateJobRequest;
export type AdminUpdateJobMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminUpdateJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminUpdateJob>>,
  TError,
  { id: string;data: UpdateJobRequest },
  TContext
  > => {
  const mutationOptions = getAdminUpdateJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getDashboardSummary = (

  signal?: AbortSignal,
) => customClient<GetDashboardSummaryResponse>(
  { url: '/api/v1/admin/dashboard', method: 'GET', signal },
);

export const getGetDashboardSummaryQueryKey = () => ['/api/v1/admin/dashboard'] as const;

export const getGetDashboardSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardSummary>>> = ({ signal }) => getDashboardSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardSummary>>>;
export type GetDashboardSummaryQueryError = unknown;

export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getDashboardSummary>>,
  TError,
  Awaited<ReturnType<typeof getDashboardSummary>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getDashboardSummary>>,
  TError,
  Awaited<ReturnType<typeof getDashboardSummary>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDashboardSummaryQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetDashboardSummarySuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardSummary>>> = ({ signal }) => getDashboardSummary(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDashboardSummarySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardSummary>>>;
export type GetDashboardSummarySuspenseQueryError = unknown;

export function useGetDashboardSummarySuspense<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDashboardSummarySuspense<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetDashboardSummarySuspense<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetDashboardSummarySuspense<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDashboardSummarySuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getServiceStatistics = (

  signal?: AbortSignal,
) => customClient<GetServiceStatisticsResponse>(
  { url: '/api/v1/admin/stats/services', method: 'GET', signal },
);

export const getGetServiceStatisticsQueryKey = () => ['/api/v1/admin/stats/services'] as const;

export const getGetServiceStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetServiceStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceStatistics>>> = ({ signal }) => getServiceStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetServiceStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceStatistics>>>;
export type GetServiceStatisticsQueryError = unknown;

export function useGetServiceStatistics<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getServiceStatistics>>,
  TError,
  Awaited<ReturnType<typeof getServiceStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServiceStatistics<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getServiceStatistics>>,
  TError,
  Awaited<ReturnType<typeof getServiceStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServiceStatistics<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetServiceStatistics<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetServiceStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetServiceStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetServiceStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceStatistics>>> = ({ signal }) => getServiceStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetServiceStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceStatistics>>>;
export type GetServiceStatisticsSuspenseQueryError = unknown;

export function useGetServiceStatisticsSuspense<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServiceStatisticsSuspense<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetServiceStatisticsSuspense<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetServiceStatisticsSuspense<TData = Awaited<ReturnType<typeof getServiceStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getServiceStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetServiceStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getBookingStatistics = (

  signal?: AbortSignal,
) => customClient<GetBookingStatisticsResponse>(
  { url: '/api/v1/admin/stats/bookings', method: 'GET', signal },
);

export const getGetBookingStatisticsQueryKey = () => ['/api/v1/admin/stats/bookings'] as const;

export const getGetBookingStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBookingStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookingStatistics>>> = ({ signal }) => getBookingStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookingStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getBookingStatistics>>>;
export type GetBookingStatisticsQueryError = unknown;

export function useGetBookingStatistics<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getBookingStatistics>>,
  TError,
  Awaited<ReturnType<typeof getBookingStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetBookingStatistics<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getBookingStatistics>>,
  TError,
  Awaited<ReturnType<typeof getBookingStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetBookingStatistics<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetBookingStatistics<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetBookingStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetBookingStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBookingStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBookingStatistics>>> = ({ signal }) => getBookingStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBookingStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getBookingStatistics>>>;
export type GetBookingStatisticsSuspenseQueryError = unknown;

export function useGetBookingStatisticsSuspense<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetBookingStatisticsSuspense<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetBookingStatisticsSuspense<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetBookingStatisticsSuspense<TData = Awaited<ReturnType<typeof getBookingStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getBookingStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetBookingStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getMasterStatistics = (

  signal?: AbortSignal,
) => customClient<GetMasterStatisticsResponse>(
  { url: '/api/v1/admin/stats/masters', method: 'GET', signal },
);

export const getGetMasterStatisticsQueryKey = () => ['/api/v1/admin/stats/masters'] as const;

export const getGetMasterStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterStatistics>>> = ({ signal }) => getMasterStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterStatistics>>>;
export type GetMasterStatisticsQueryError = unknown;

export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterStatistics>>,
  TError,
  Awaited<ReturnType<typeof getMasterStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterStatistics>>,
  TError,
  Awaited<ReturnType<typeof getMasterStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMasterStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterStatistics>>> = ({ signal }) => getMasterStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterStatistics>>>;
export type GetMasterStatisticsSuspenseQueryError = unknown;

export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getClientStatistics = (

  signal?: AbortSignal,
) => customClient<GetClientStatisticsResponse>(
  { url: '/api/v1/admin/stats/clients', method: 'GET', signal },
);

export const getGetClientStatisticsQueryKey = () => ['/api/v1/admin/stats/clients'] as const;

export const getGetClientStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetClientStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientStatistics>>> = ({ signal }) => getClientStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetClientStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getClientStatistics>>>;
export type GetClientStatisticsQueryError = unknown;

export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getClientStatistics>>,
  TError,
  Awaited<ReturnType<typeof getClientStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getClientStatistics>>,
  TError,
  Awaited<ReturnType<typeof getClientStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetClientStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetClientStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetClientStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientStatistics>>> = ({ signal }) => getClientStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetClientStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getClientStatistics>>>;
export type GetClientStatisticsSuspenseQueryError = unknown;

export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetClientStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getUserStatistics = (

  signal?: AbortSignal,
) => customClient<GetUserStatisticsResponse>(
  { url: '/api/v1/admin/stats/users', method: 'GET', signal },
);

export const getGetUserStatisticsQueryKey = () => ['/api/v1/admin/stats/users'] as const;

export const getGetUserStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserStatistics>>> = ({ signal }) => getUserStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getUserStatistics>>>;
export type GetUserStatisticsQueryError = unknown;

export function useGetUserStatistics<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getUserStatistics>>,
  TError,
  Awaited<ReturnType<typeof getUserStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserStatistics<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getUserStatistics>>,
  TError,
  Awaited<ReturnType<typeof getUserStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserStatistics<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserStatistics<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetUserStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserStatistics>>> = ({ signal }) => getUserStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserStatistics>>>;
export type GetUserStatisticsSuspenseQueryError = unknown;

export function useGetUserStatisticsSuspense<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserStatisticsSuspense<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserStatisticsSuspense<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserStatisticsSuspense<TData = Awaited<ReturnType<typeof getUserStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetUserStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const findUsers = (
  params?: FindUsersParams,
  signal?: AbortSignal,
) => customClient<FindUsersResponsePagedResponse>(
  {
    url: '/api/v1/admin/users',
    method: 'GET',
    params,
    signal,
  },
);

export const getFindUsersQueryKey = (params?: FindUsersParams) => ['/api/v1/admin/users', ...(params ? [params] : [])] as const;

export const getFindUsersQueryOptions = <TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(params?: FindUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findUsers>>> = ({ signal }) => findUsers(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindUsersQueryResult = NonNullable<Awaited<ReturnType<typeof findUsers>>>;
export type FindUsersQueryError = unknown;

export function useFindUsers<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params: undefined | FindUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findUsers>>,
  TError,
  Awaited<ReturnType<typeof findUsers>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindUsers<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params?: FindUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findUsers>>,
  TError,
  Awaited<ReturnType<typeof findUsers>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindUsers<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params?: FindUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFindUsers<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params?: FindUsersParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindUsersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindUsersSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(params?: FindUsersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findUsers>>> = ({ signal }) => findUsers(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindUsersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findUsers>>>;
export type FindUsersSuspenseQueryError = unknown;

export function useFindUsersSuspense<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params: undefined | FindUsersParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindUsersSuspense<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params?: FindUsersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindUsersSuspense<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params?: FindUsersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFindUsersSuspense<TData = Awaited<ReturnType<typeof findUsers>>, TError = unknown>(
  params?: FindUsersParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findUsers>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindUsersSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const setUserRole = (
  id: string,
  setUserRoleRequest: SetUserRoleRequest,
) => customClient<SetUserRoleResponse>(
  {
    url: `/api/v1/admin/users/${id}/role`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: setUserRoleRequest,
  },
);

export const getSetUserRoleMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserRole>>, TError, { id: string;data: SetUserRoleRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof setUserRole>>, TError, { id: string;data: SetUserRoleRequest }, TContext> => {
  const mutationKey = ['setUserRole'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof setUserRole>>, { id: string;data: SetUserRoleRequest }> = (props) => {
    const { id, data } = props ?? {};

    return setUserRole(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SetUserRoleMutationResult = NonNullable<Awaited<ReturnType<typeof setUserRole>>>;
export type SetUserRoleMutationBody = SetUserRoleRequest;
export type SetUserRoleMutationError = ProblemDetails | ValidationProblemDetails;

export const useSetUserRole = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setUserRole>>, TError, { id: string;data: SetUserRoleRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof setUserRole>>,
  TError,
  { id: string;data: SetUserRoleRequest },
  TContext
  > => {
  const mutationOptions = getSetUserRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteUser = (
  id: string,
) => customClient<void>(
  { url: `/api/v1/admin/users/${id}`, method: 'DELETE' },
);

export const getDeleteUserMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError, { id: string }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError, { id: string }, TContext> => {
  const mutationKey = ['deleteUser'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, { id: string }> = (props) => {
    const { id } = props ?? {};

    return deleteUser(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;

export type DeleteUserMutationError = ProblemDetails;

export const useDeleteUser = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError, { id: string }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof deleteUser>>,
  TError,
  { id: string },
  TContext
  > => {
  const mutationOptions = getDeleteUserMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
