/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {
  useMutation,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  CreateJobCategoryRequest,
  CreateJobCategoryResponse,
  CreateJobRequest,
  CreateJobResponse,
  GetClientStatisticsResponse,
  GetMasterStatisticsResponse,
  ProblemDetails,
  UpdateJobRequest,
  UpdateJobResponse,
  ValidationProblemDetails,
} from './api.schemas';

export const adminCreateJobCategory = (
  createJobCategoryRequest: CreateJobCategoryRequest,
  signal?: AbortSignal,
) => customClient<CreateJobCategoryResponse>(
  {
    url: '/api/v1/admin/job-categories',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createJobCategoryRequest,
    signal,
  },
);

export const getAdminCreateJobCategoryMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJobCategory>>, TError, { data: CreateJobCategoryRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminCreateJobCategory>>, TError, { data: CreateJobCategoryRequest }, TContext> => {
  const mutationKey = ['adminCreateJobCategory'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateJobCategory>>, { data: CreateJobCategoryRequest }> = (props) => {
    const { data } = props ?? {};

    return adminCreateJobCategory(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminCreateJobCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateJobCategory>>>;
export type AdminCreateJobCategoryMutationBody = CreateJobCategoryRequest;
export type AdminCreateJobCategoryMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminCreateJobCategory = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJobCategory>>, TError, { data: CreateJobCategoryRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminCreateJobCategory>>,
  TError,
  { data: CreateJobCategoryRequest },
  TContext
  > => {
  const mutationOptions = getAdminCreateJobCategoryMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminCreateJob = (
  createJobRequest: CreateJobRequest,
  signal?: AbortSignal,
) => customClient<CreateJobResponse>(
  {
    url: '/api/v1/admin/jobs',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createJobRequest,
    signal,
  },
);

export const getAdminCreateJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJob>>, TError, { data: CreateJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminCreateJob>>, TError, { data: CreateJobRequest }, TContext> => {
  const mutationKey = ['adminCreateJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreateJob>>, { data: CreateJobRequest }> = (props) => {
    const { data } = props ?? {};

    return adminCreateJob(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminCreateJobMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreateJob>>>;
export type AdminCreateJobMutationBody = CreateJobRequest;
export type AdminCreateJobMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminCreateJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreateJob>>, TError, { data: CreateJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminCreateJob>>,
  TError,
  { data: CreateJobRequest },
  TContext
  > => {
  const mutationOptions = getAdminCreateJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const adminUpdateJob = (
  id: string,
  updateJobRequest: UpdateJobRequest,
) => customClient<UpdateJobResponse>(
  {
    url: `/api/v1/admin/jobs/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateJobRequest,
  },
);

export const getAdminUpdateJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext> => {
  const mutationKey = ['adminUpdateJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateJob>>, { id: string;data: UpdateJobRequest }> = (props) => {
    const { id, data } = props ?? {};

    return adminUpdateJob(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminUpdateJobMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateJob>>>;
export type AdminUpdateJobMutationBody = UpdateJobRequest;
export type AdminUpdateJobMutationError = ProblemDetails | ValidationProblemDetails;

export const useAdminUpdateJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof adminUpdateJob>>,
  TError,
  { id: string;data: UpdateJobRequest },
  TContext
  > => {
  const mutationOptions = getAdminUpdateJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getMasterStatistics = (

  signal?: AbortSignal,
) => customClient<GetMasterStatisticsResponse>(
  { url: '/api/v1/admin/stats/masters', method: 'GET', signal },
);

export const getGetMasterStatisticsQueryKey = () => ['/api/v1/admin/stats/masters'] as const;

export const getGetMasterStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterStatistics>>> = ({ signal }) => getMasterStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterStatistics>>>;
export type GetMasterStatisticsQueryError = unknown;

export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterStatistics>>,
  TError,
  Awaited<ReturnType<typeof getMasterStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterStatistics>>,
  TError,
  Awaited<ReturnType<typeof getMasterStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMasterStatistics<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMasterStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterStatistics>>> = ({ signal }) => getMasterStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterStatistics>>>;
export type GetMasterStatisticsSuspenseQueryError = unknown;

export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetMasterStatisticsSuspense<TData = Awaited<ReturnType<typeof getMasterStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getClientStatistics = (

  signal?: AbortSignal,
) => customClient<GetClientStatisticsResponse>(
  { url: '/api/v1/admin/stats/clients', method: 'GET', signal },
);

export const getGetClientStatisticsQueryKey = () => ['/api/v1/admin/stats/clients'] as const;

export const getGetClientStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetClientStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientStatistics>>> = ({ signal }) => getClientStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetClientStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getClientStatistics>>>;
export type GetClientStatisticsQueryError = unknown;

export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getClientStatistics>>,
  TError,
  Awaited<ReturnType<typeof getClientStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getClientStatistics>>,
  TError,
  Awaited<ReturnType<typeof getClientStatistics>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetClientStatistics<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetClientStatisticsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetClientStatisticsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetClientStatisticsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientStatistics>>> = ({ signal }) => getClientStatistics(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetClientStatisticsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getClientStatistics>>>;
export type GetClientStatisticsSuspenseQueryError = unknown;

export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetClientStatisticsSuspense<TData = Awaited<ReturnType<typeof getClientStatistics>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getClientStatistics>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetClientStatisticsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
