/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
export type BookingCommandDTO = {
  /** Id of master */
  masterId: string;
  /** Id of client */
  clientId: string;
  /** Id of the master job */
  masterJobId: string;
  /** Id of the master availability slot */
  masterAvailabilityId: string;
};

export type BookingDTO = {
  /** ID */
  id: string;
  /** Master ID */
  masterId: string;
  /** Client ID */
  clientId: string;
  /** Master job ID */
  masterJobId: string;
  /**
   * Client name
   * @minLength 1
   */
  clientName: string;
  /**
   * Master name
   * @minLength 1
   */
  masterName: string;
  /**
   * Master job title
   * @minLength 1
   */
  masterJobTitle: string;
  /**
   * Master job category name
   * @minLength 1
   */
  masterJobCategoryName: string;
  /**
   * Master job category image URL
   * @nullable
   */
  masterJobCategoryImageUrl?: string | null;
  /**
   * Booking city
   * @nullable
   */
  locationCity?: string | null;
  /**
   * Booking country
   * @nullable
   */
  locationCountry?: string | null;
  /**
   * Address line 1
   * @nullable
   */
  locationAddressLine1?: string | null;
  /**
   * Address line 2
   * @nullable
   */
  locationAddressLine2?: string | null;
  /**
   * Postal code
   * @nullable
   */
  locationPostalCode?: string | null;
  /** Scheduled at */
  scheduledAt: Date;
  /** Duration */
  duration: string;
  /** Price */
  price: number;
  status: BookingStatus;
};

export enum BookingStatus {
  Requested = 'Requested',
  Confirmed = 'Confirmed',
  Completed = 'Completed',
  Cancelled = 'Cancelled',

}
export type CancelBookingRequest = {
  /** Booking identifier */
  bookingId: string;
  /**
   * Master identifier (if cancelled by master)
   * @nullable
   */
  masterId?: string | null;
  /**
   * Client identifier (if cancelled by client)
   * @nullable
   */
  clientId?: string | null;
};

export type CancelBookingResponse = {
  bookingId?: string;
};

export type ClientCommandDTO = {
  /**
   * First name
   * @minLength 1
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   */
  lastName: string;
  /**
   * Email address
   * @minLength 1
   */
  email: string;
  /**
   * Phone number
   * @minLength 1
   * @maxLength 32
   */
  phoneNumber: string;
};

export type ClientDTO = {
  /** ID */
  id: string;
  /**
   * First name
   * @minLength 1
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   */
  lastName: string;
  /**
   * Email address
   * @minLength 1
   */
  email: string;
  /**
   * Phone number
   * @minLength 1
   */
  phoneNumber: string;
  /**
   * Profile image URL
   * @nullable
   */
  profileImageUrl?: string | null;
};

export type ConfirmBookingRequest = {
  /** Booking identifier */
  bookingId: string;
  /** Master identifier */
  masterId: string;
};

export type ConfirmBookingResponse = {
  bookingId?: string;
};

export type CreateBookingRequestAllOf = { [key: string]: unknown };

export type CreateBookingRequest = BookingCommandDTO & CreateBookingRequestAllOf;

export type CreateBookingResponse = {
  /** Id of created booking */
  id: string;
};

export type CreateClientRequestAllOf = { [key: string]: unknown };

export type CreateClientRequest = ClientCommandDTO & CreateClientRequestAllOf;

export type CreateClientResponse = {
  /** Id */
  id: string;
};

export type CreateJobRequestAllOf = { [key: string]: unknown };

export type CreateJobRequest = JobCommandDTO & CreateJobRequestAllOf;

export type CreateJobResponse = {
  id?: string;
};

export type CreateMasterAvailabilityRequest = {
  /** Master identifier */
  masterId: string;
  /** Availability slots */
  availability: MasterAvailabilitySlotCommandDTO[];
};

export type CreateMasterAvailabilityResponse = {
  /** Master identifier */
  masterId: string;
};

export type CreateMasterJobRequest = {
  masterId: string;
  job: MasterJobOfferingCommandDTO;
};

export type CreateMasterJobResponse = {
  masterId?: string;
  masterJobId?: string;
};

export type CreateMasterRequestAllOf = { [key: string]: unknown };

export type CreateMasterRequest = MasterProfileCommandDTO & CreateMasterRequestAllOf;

export type CreateMasterResponse = {
  id?: string;
};

export type CreateRatingRequest = {
  /** Booking ID to rate */
  bookingId: string;
  /**
   * Rating value (1-5)
   * @minimum 1
   * @maximum 5
   */
  value: number;
  /**
   * Optional comment
   * @nullable
   */
  comment?: string | null;
};

export type CreateRatingResponse = {
  /** ID of created rating */
  id: string;
};

export type EarningsDataPoint = {
  /**
   * Label for the data point (e.g., "Mon", "Jan", "2024")
   * @minLength 1
   */
  label: string;
  /** Earnings value for this period */
  value: number;
};

export enum EarningsPeriod {
  Weekly = 'Weekly',
  Monthly = 'Monthly',
  Yearly = 'Yearly',

}
export type FindBookingsResponseAllOf = { [key: string]: unknown };

export type FindBookingsResponse = BookingDTO & FindBookingsResponseAllOf;

export type FindBookingsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindBookingsResponse[];
};

export type FindClientsResponseAllOf = { [key: string]: unknown };

export type FindClientsResponse = ClientDTO & FindClientsResponseAllOf;

export type FindClientsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindClientsResponse[];
};

export type FindJobCategoriesResponseAllOf = { [key: string]: unknown };

export type FindJobCategoriesResponse = JobCategoryDTO & FindJobCategoriesResponseAllOf;

export type FindJobCategoriesResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindJobCategoriesResponse[];
};

export type FindJobsResponseAllOf = { [key: string]: unknown };

export type FindJobsResponse = JobDTO & FindJobsResponseAllOf;

export type FindJobsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindJobsResponse[];
};

export type FindMasterAvailabilitiesResponseAllOf = { [key: string]: unknown };

export type FindMasterAvailabilitiesResponse = MasterAvailabilitySlotDTO & FindMasterAvailabilitiesResponseAllOf;

export type FindMasterAvailabilitiesResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindMasterAvailabilitiesResponse[];
};

export type FindMasterJobImagesResponse = {
  /** @nullable */
  images?: MasterJobImageWithUrlDTO[] | null;
};

export type FindMasterJobsResponse = {
  /** @nullable */
  jobs?: MasterJobDTO[] | null;
};

export type FindMasterRatingsResponseAllOf = { [key: string]: unknown };

export type FindMasterRatingsResponse = RatingDTO & FindMasterRatingsResponseAllOf;

export type FindMasterRatingsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindMasterRatingsResponse[];
};

export type FindMastersResponseAllOf = { [key: string]: unknown };

export type FindMastersResponse = MasterDTO & FindMastersResponseAllOf;

export type FindMastersResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindMastersResponse[];
};

export enum Gender {
  Male = 'Male',
  Female = 'Female',
  Other = 'Other',

}
export type GetBookingByIdResponseAllOf = { [key: string]: unknown };

export type GetBookingByIdResponse = BookingDTO & GetBookingByIdResponseAllOf;

export type GetClientByIdResponseAllOf = { [key: string]: unknown };

export type GetClientByIdResponse = ClientDTO & GetClientByIdResponseAllOf;

export type GetDashboardStatsResponse = {
  /** Total number of bookings (excluding cancelled) */
  totalBookings: number;
  /** Percentage change in bookings compared to previous month */
  totalBookingsChange: number;
  /** Average monthly earnings from completed bookings */
  monthlyEarningsAverage: number;
  /** Percentage change in earnings compared to previous month */
  monthlyEarningsChange: number;
  /** Number of pending booking requests */
  pendingRequestsCount: number;
};

export type GetEarningsPerformanceResponse = {
  period: EarningsPeriod;
  /**
   * Earnings data points grouped by the selected period
   * @nullable
   */
  data?: EarningsDataPoint[] | null;
  /** Total earnings for the entire period */
  total: number;
};

export type GetJobByIdResponseAllOf = { [key: string]: unknown };

export type GetJobByIdResponse = JobDTO & GetJobByIdResponseAllOf;

export type GetMasterAvailabilityResponseAllOf = { [key: string]: unknown };

export type GetMasterAvailabilityResponse = MasterAvailabilitySlotDTO & GetMasterAvailabilityResponseAllOf;

export type GetMasterByIdResponseAllOf = { [key: string]: unknown };

export type GetMasterByIdResponse = MasterDTO & GetMasterByIdResponseAllOf;

export type GetMasterJobImageByIdResponse = {
  /**
   * Image file name
   * @minLength 1
   */
  fileName: string;
  /**
   * Image file mime type
   * @minLength 1
   */
  fileMimeType: string;
  /** Image file size */
  fileSize: number;
  /**
   * Direct URL to the image in blob storage
   * @minLength 1
   */
  url: string;
};

export type GetMasterRatingsResponseAllOf = { [key: string]: unknown };

export type GetMasterRatingsResponse = RatingDTO & GetMasterRatingsResponseAllOf;

export type GetMasterRatingsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: GetMasterRatingsResponse[];
};

export type GetPendingRequestsResponse = {
  /**
   * List of pending booking requests
   * @nullable
   */
  requests?: PendingRequestDTO[] | null;
  /** Total count of pending requests */
  totalCount: number;
};

export type GetUserResponse = {
  id?: string;
  role?: UserRole;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  fullName?: string | null;
};

export type JobCategoryDTO = {
  id?: string;
  /** @nullable */
  name: string | null;
  /** @nullable */
  imageUrl?: string | null;
};

export type JobCommandDTO = {
  /**
   * Name
   * @minLength 1
   */
  name: string;
  /** Category identifier */
  categoryId: string;
  /**
   * Desciption
   * @nullable
   */
  description?: string | null;
  /**
   * Duration in minutes
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes: number;
};

export type JobDTO = {
  id: string;
  /** @minLength 1 */
  name: string;
  categoryId: string;
  /** @minLength 1 */
  categoryName: string;
  /** @minLength 1 */
  description: string;
  /**
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes: number;
};

export type MasterAvailabilitySlotCommandDTO = {
  /** Slot starts at */
  start: Date;
  /** Slot ends at */
  end: Date;
};

export type MasterAvailabilitySlotDTO = {
  /** Identifier */
  id: string;
  /** Master identifer */
  masterId: string;
  /**
   * Master name
   * @minLength 1
   */
  masterName: string;
  /** Starts at */
  startAt: Date;
  /** Ends at */
  endAt: Date;
};

export type MasterDTO = {
  id?: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  age?: number | null;
  gender?: Gender;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  rating?: number;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  country?: string | null;
  /** @nullable */
  addressLine1?: string | null;
  /** @nullable */
  addressLine2?: string | null;
  /** @nullable */
  postalCode?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
};

export type MasterJobDTO = {
  /** Master job identifier */
  id: string;
  /** Job identifier */
  jobId: string;
  /** Job category identifier */
  jobCategoryId: string;
  /**
   * Job category name
   * @minLength 1
   */
  jobCategoryName: string;
  /**
   * Job name
   * @minLength 1
   */
  jobName: string;
  /**
   * Job title
   * @minLength 1
   */
  title: string;
  /** Job price */
  price: number;
  /** Job duration in minutes */
  durationMinutes: number;
  /** Job images */
  images: MasterJobImageDTO[];
};

export type MasterJobImageDTO = {
  /** Image identifier */
  id: string;
  /**
   * Image file name
   * @minLength 1
   */
  fileName: string;
  /**
   * Image file mime type
   * @minLength 1
   */
  fileMimeType: string;
  /** Image file size */
  fileSize: number;
  /**
   * Direct URL to the image in blob storage
   * @minLength 1
   */
  url: string;
};

export type MasterJobImageWithUrlDTO = {
  /** Image identifier */
  id: string;
  /** Master job identifier */
  jobId: string;
  /**
   * Image file name
   * @minLength 1
   */
  fileName: string;
  /**
   * Image file mime type
   * @minLength 1
   */
  fileMimeType: string;
  /** Image file size */
  fileSize: number;
  /**
   * Direct URL to the image in blob storage
   * @minLength 1
   */
  url: string;
};

export type MasterJobOfferingCommandDTO = {
  jobId: string;
  /**
   * @minLength 1
   * @maxLength 256
   */
  title: string;
  /** @minimum 0 */
  price?: number;
  /**
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes?: number;
};

export type MasterProfileCommandDTO = {
  /**
   * @minLength 1
   * @maxLength 128
   */
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  lastName: string;
  /**
   * @minimum 18
   * @maximum 120
   * @nullable
   */
  age?: number | null;
  gender?: Gender;
  /**
   * @maxLength 1000
   * @nullable
   */
  description?: string | null;
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 1
   * @maxLength 32
   */
  phoneNumber: string;
  /**
   * @minimum -90
   * @maximum 90
   * @nullable
   */
  latitude?: number | null;
  /**
   * @minimum -180
   * @maximum 180
   * @nullable
   */
  longitude?: number | null;
  /**
   * @maxLength 128
   * @nullable
   */
  city?: string | null;
  /**
   * @maxLength 128
   * @nullable
   */
  country?: string | null;
  /**
   * @maxLength 256
   * @nullable
   */
  addressLine1?: string | null;
  /**
   * @maxLength 256
   * @nullable
   */
  addressLine2?: string | null;
  /**
   * @maxLength 32
   * @nullable
   */
  postalCode?: string | null;
};

export type PendingRequestDTO = {
  /** Booking ID */
  id: string;
  /** Client ID */
  clientId: string;
  /**
   * Client name
   * @minLength 1
   */
  clientName: string;
  /**
   * Service/job title
   * @minLength 1
   */
  masterJobTitle: string;
  /** When the booking was requested */
  requestedAt: Date;
  /** Scheduled date and time */
  scheduledAt: Date;
  /** Service price */
  price: number;
};

export type ProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
};

export type RatingDTO = {
  /** Rating ID */
  id: string;
  /** Booking ID */
  bookingId: string;
  /** Client ID who submitted the rating */
  clientId: string;
  /**
   * Client name
   * @minLength 1
   */
  clientName: string;
  /**
   * Master name
   * @minLength 1
   */
  masterName: string;
  /** Rating value (1-5) */
  value: number;
  /**
   * Optional comment
   * @nullable
   */
  comment?: string | null;
  /** When the rating was submitted */
  submittedAt: Date;
};

export type RescheduleBookingRequest = {
  /** Booking ID */
  bookingId: string;
  /** Schedule date and time */
  scheduledAt: Date;
  /** Duration of booking */
  duration: string;
};

export type RescheduleBookingResponse = {
  /** Id of created booking */
  id: string;
};

export type UpdateClientProfileRequestAllOf = {
  /** Client id */
  clientID: string;
};

export type UpdateClientProfileRequest = ClientCommandDTO & UpdateClientProfileRequestAllOf;

export type UpdateClientProfileResponse = {
  /** Id */
  id: string;
};

export type UpdateJobRequestAllOf = {
  /** Job ID */
  jobId: string;
};

export type UpdateJobRequest = JobCommandDTO & UpdateJobRequestAllOf;

export type UpdateJobResponse = {
  jobId: string;
};

export type UpdateMasterAvailabilityRequest = {
  /** Master identifier */
  masterId: string;
  /** Master availability identifier */
  masterAvailabilityId: string;
  availability: MasterAvailabilitySlotCommandDTO;
};

export type UpdateMasterAvailabilityResponse = {
  /** Master identifer */
  masterId: string;
  /** Master availability identifier */
  masterAvailabilityId: string;
};

export type UpdateMasterJobRequest = {
  masterId: string;
  masterJobId: string;
  job: MasterJobOfferingCommandDTO;
};

export type UpdateMasterJobResponse = {
  masterId?: string;
  masterJobId?: string;
};

export type UpdateMasterProfileRequestAllOf = {
  masterId: string;
};

export type UpdateMasterProfileRequest = MasterProfileCommandDTO & UpdateMasterProfileRequestAllOf;

export type UpdateMasterProfileResponse = {
  masterId?: string;
};

export type UploadClientProfileImageResponse = {
  /** Client id */
  clientId: string;
};

export type UploadMasterJobImageResponse = {
  masterId?: string;
  masterJobId?: string;
};

export type UploadMasterProfileImageResponse = {
  /** Master id */
  masterId: string;
};

export enum UserRole {
  Client = 'Client',
  Master = 'Master',

}
/**
 * @nullable
 */
export type ValidationProblemDetailsErrors = { [key: string]: string[] } | null;

export type ValidationProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  errors?: ValidationProblemDetailsErrors;
  [key: string]: unknown;
};

export type FindBookingsParams = {
/**
 * Filter by master id
 */
  masterId?: string;
  /**
 * Filter by client id
 */
  clientId?: string;
  /**
 * Filter by status
 */
  status?: BookingStatus;
  /**
 * Filter by from
 */
  from?: Date;
  /**
 * Filter by to
 */
  to?: Date;
  /**
 * Search by client name or job title
 */
  search?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetBookingByIdParams = {
/**
 * Id
 */
  id: string;
};

export type FindClientsParams = {
/**
 * Filter by first name
 */
  firstName?: string;
  /**
 * Filter by last name
 */
  lastName?: string;
  /**
 * Filter by email address
 */
  email?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetClientByIdParams = {
  id?: string;
};

export type UploadClientProfileImageBody = {
  /** Client id */
  clientId: string;
  /** File uploads */
  files: Blob[];
};

export type FindJobsParams = {
/**
 * Filter by text
 */
  text?: string;
  /**
 * Filter by category
 */
  categoryId?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type FindJobCategoriesParams = {
/**
 * Filter by name
 */
  name?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetJobByIdParams = {
  id?: string;
};

export type FindMastersParams = {
  text?: string;
  city?: string;
  jobCategoryId?: string;
  minPrice?: number;
  maxPrice?: number;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetMasterByIdParams = {
  id: string;
};

export type FindMasterAvailabilitiesParams = {
/**
 * Master identifier
 */
  masterId: string;
  /**
 * Filter by start date (slots starting on or after this date)
 */
  startAt?: Date;
  /**
 * Filter by end date (slots ending on or before this date)
 */
  endAt?: Date;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type UploadMasterProfileImageBody = {
  /** Master id */
  masterId: string;
  /** File uploads */
  files: Blob[];
};

export type UploadMasterJobImageBody = {
  /** Master id */
  masterId: string;
  /** Master job id */
  masterJobId: string;
  /** File uploads */
  files: Blob[];
};

export type GetEarningsPerformanceParams = {
  masterId: string;
  /**
 * Time period for earnings data grouping
 */
  period?: EarningsPeriod;
};

export type FindRatingsParams = {
/**
 * Filter by client ID
 */
  clientId?: string;
  /**
 * Filter by booking ID
 */
  bookingId?: string;
  /**
 * Filter by master ID
 */
  masterId?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetMasterRatingsParams = {
/**
 * Master ID to get ratings for
 */
  masterId: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};
