/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
export type BookingCommandDTO = {
  /** Id of master */
  masterId: string;
  /** Id of client */
  clientId: string;
  /** Id of the job */
  masterJobId: string;
  /** Booking date and time */
  scheduledAt: Date;
  /**
   * Duration of the job
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes?: string;
  /**
   * Price of the job
   * @minimum 0
   */
  price?: number;
};

export type BookingDTO = {
  /** ID */
  id: string;
  /** Master ID */
  masterId: string;
  /** Client ID */
  clientId: string;
  /** Master job ID */
  masterJobId: string;
  /**
   * Client name
   * @minLength 1
   */
  clientName: string;
  /**
   * Master name
   * @minLength 1
   */
  masterName: string;
  /**
   * Master job title
   * @minLength 1
   */
  masterJobTitle: string;
  /** Scheduled at */
  scheduledAt: Date;
  /** Duration */
  duration: string;
  /** Price */
  price: number;
  status: BookingStatus;
};

export enum BookingStatus {
  Requested = 'Requested',
  Confirmed = 'Confirmed',
  Completed = 'Completed',
  Cancelled = 'Cancelled',

}
export type ClientCommandDTO = {
  /**
   * First name
   * @minLength 1
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   */
  lastName: string;
  /**
   * Email address
   * @minLength 1
   */
  email: string;
  /**
   * Phone number
   * @minLength 1
   * @maxLength 32
   */
  phoneNumber: string;
};

export type ClientDTO = {
  /** ID */
  id: string;
  /**
   * First name
   * @minLength 1
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   */
  lastName: string;
  /**
   * Email address
   * @minLength 1
   */
  email: string;
  /**
   * Phone number
   * @minLength 1
   */
  phoneNumber: string;
  /**
   * Profile image URL
   * @nullable
   */
  profileImageUrl?: string | null;
};

export type CreateBookingRequestAllOf = { [key: string]: unknown };

export type CreateBookingRequest = BookingCommandDTO & CreateBookingRequestAllOf;

export type CreateBookingResponse = {
  /** Id of created booking */
  id: string;
};

export type CreateClientRequestAllOf = { [key: string]: unknown };

export type CreateClientRequest = ClientCommandDTO & CreateClientRequestAllOf;

export type CreateClientResponse = {
  /** Id */
  id: string;
};

export type CreateJobRequestAllOf = { [key: string]: unknown };

export type CreateJobRequest = JobCommandDTO & CreateJobRequestAllOf;

export type CreateJobResponse = {
  id?: string;
};

export type CreateMasterAvailabilityRequest = {
  /** Master identifier */
  masterId: string;
  /** Availability slots */
  availability: MasterAvailabilitySlotCommandDTO[];
};

export type CreateMasterAvailabilityResponse = {
  /** Master identifier */
  masterId: string;
};

export type CreateMasterJobRequest = {
  masterId: string;
  job: MasterJobOfferingCommandDTO;
};

export type CreateMasterJobResponse = {
  masterId?: string;
  masterJobId?: string;
};

export type CreateMasterRequestAllOf = { [key: string]: unknown };

export type CreateMasterRequest = MasterProfileCommandDTO & CreateMasterRequestAllOf;

export type CreateMasterResponse = {
  id?: string;
};

export type FindBookingsResponseAllOf = { [key: string]: unknown };

export type FindBookingsResponse = BookingDTO & FindBookingsResponseAllOf;

export type FindBookingsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindBookingsResponse[];
};

export type FindClientsResponseAllOf = { [key: string]: unknown };

export type FindClientsResponse = ClientDTO & FindClientsResponseAllOf;

export type FindClientsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindClientsResponse[];
};

export type FindJobCategoriesResponseAllOf = { [key: string]: unknown };

export type FindJobCategoriesResponse = JobCategoryDTO & FindJobCategoriesResponseAllOf;

export type FindJobCategoriesResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindJobCategoriesResponse[];
};

export type FindJobsResponseAllOf = { [key: string]: unknown };

export type FindJobsResponse = JobDTO & FindJobsResponseAllOf;

export type FindJobsResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindJobsResponse[];
};

export type FindMasterAvailabilitiesResponseAllOf = { [key: string]: unknown };

export type FindMasterAvailabilitiesResponse = MasterAvailabilitySlotDTO & FindMasterAvailabilitiesResponseAllOf;

export type FindMasterAvailabilitiesResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindMasterAvailabilitiesResponse[];
};

export type FindMasterJobImagesResponse = {
  /** @nullable */
  images?: MasterJobImageWithUrlDTO[] | null;
};

export type FindMasterJobsResponse = {
  /** @nullable */
  jobs?: MasterJobDTO[] | null;
};

export type FindMastersResponseAllOf = { [key: string]: unknown };

export type FindMastersResponse = MasterDTO & FindMastersResponseAllOf;

export type FindMastersResponsePagedResponse = {
  /** Current page number */
  page: number;
  /** Page size */
  pageSize: number;
  /** Total pages count */
  pageCount: number;
  /** Total items count */
  totalItemCount: number;
  /** Items */
  items: FindMastersResponse[];
};

export enum Gender {
  Male = 'Male',
  Female = 'Female',
  Other = 'Other',

}
export type GetBookingByIdResponseAllOf = { [key: string]: unknown };

export type GetBookingByIdResponse = BookingDTO & GetBookingByIdResponseAllOf;

export type GetClientByIdResponseAllOf = { [key: string]: unknown };

export type GetClientByIdResponse = ClientDTO & GetClientByIdResponseAllOf;

export type GetJobByIdResponseAllOf = { [key: string]: unknown };

export type GetJobByIdResponse = JobDTO & GetJobByIdResponseAllOf;

export type GetMasterAvailabilityResponseAllOf = { [key: string]: unknown };

export type GetMasterAvailabilityResponse = MasterAvailabilitySlotDTO & GetMasterAvailabilityResponseAllOf;

export type GetMasterByIdResponseAllOf = { [key: string]: unknown };

export type GetMasterByIdResponse = MasterDTO & GetMasterByIdResponseAllOf;

export type GetMasterJobImageByIdResponse = {
  /**
   * Image file name
   * @minLength 1
   */
  fileName: string;
  /**
   * Image file mime type
   * @minLength 1
   */
  fileMimeType: string;
  /** Image file size */
  fileSize: number;
  /**
   * Direct URL to the image in blob storage
   * @minLength 1
   */
  url: string;
};

export type GetUserResponse = {
  id?: string;
  role?: UserRole;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  fullName?: string | null;
};

export type JobCategoryDTO = {
  id?: string;
  /** @nullable */
  name: string | null;
};

export type JobCommandDTO = {
  /**
   * Name
   * @minLength 1
   */
  name: string;
  /** Category identifier */
  categoryId: string;
  /**
   * Desciption
   * @nullable
   */
  description?: string | null;
  /**
   * Duration in minutes
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes: number;
};

export type JobDTO = {
  id: string;
  /** @minLength 1 */
  name: string;
  categoryId: string;
  /** @minLength 1 */
  categoryName: string;
  /** @minLength 1 */
  description: string;
  /**
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes: number;
};

export type MasterAvailabilitySlotCommandDTO = {
  /** Slot starts at */
  start: Date;
  /** Slot ends at */
  end: Date;
};

export type MasterAvailabilitySlotDTO = {
  /** Identifier */
  id: string;
  /** Master identifer */
  masterId: string;
  /**
   * Master name
   * @minLength 1
   */
  masterName: string;
  /** Starts at */
  startAt: Date;
  /** Ends at */
  endAt: Date;
};

export type MasterDTO = {
  id?: string;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  age?: number | null;
  gender?: Gender;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  rating?: number;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
  /** @nullable */
  city?: string | null;
  /** @nullable */
  profileImageUrl?: string | null;
};

export type MasterJobDTO = {
  /** Master job identifier */
  id: string;
  /** Job identifier */
  jobId: string;
  /** Job category identifier */
  jobCategoryId: string;
  /**
   * Job category name
   * @minLength 1
   */
  jobCategoryName: string;
  /**
   * Job name
   * @minLength 1
   */
  jobName: string;
  /**
   * Job title
   * @minLength 1
   */
  title: string;
  /** Job price */
  price: number;
  /** Job duration in minutes */
  durationMinutes: number;
  /** Job images */
  images: MasterJobImageDTO[];
};

export type MasterJobImageDTO = {
  /** Image identifier */
  id: string;
  /**
   * Image file name
   * @minLength 1
   */
  fileName: string;
  /**
   * Image file mime type
   * @minLength 1
   */
  fileMimeType: string;
  /** Image file size */
  fileSize: number;
  /**
   * Direct URL to the image in blob storage
   * @minLength 1
   */
  url: string;
};

export type MasterJobImageWithUrlDTO = {
  /** Image identifier */
  id: string;
  /** Master job identifier */
  jobId: string;
  /**
   * Image file name
   * @minLength 1
   */
  fileName: string;
  /**
   * Image file mime type
   * @minLength 1
   */
  fileMimeType: string;
  /** Image file size */
  fileSize: number;
  /**
   * Direct URL to the image in blob storage
   * @minLength 1
   */
  url: string;
};

export type MasterJobOfferingCommandDTO = {
  jobId: string;
  /**
   * @minLength 1
   * @maxLength 256
   */
  title: string;
  /** @minimum 0 */
  price?: number;
  /**
   * @minimum 1
   * @maximum 1440
   */
  durationMinutes?: number;
};

export type MasterProfileCommandDTO = {
  /**
   * @minLength 1
   * @maxLength 128
   */
  firstName: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  lastName: string;
  /**
   * @minimum 18
   * @maximum 120
   * @nullable
   */
  age?: number | null;
  gender?: Gender;
  /**
   * @maxLength 1000
   * @nullable
   */
  description?: string | null;
  /** @minLength 1 */
  email: string;
  /**
   * @minLength 1
   * @maxLength 32
   */
  phoneNumber: string;
};

export type ProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
};

export type RescheduleBookingRequest = {
  /** Booking ID */
  bookingId: string;
  /** Schedule date and time */
  scheduledAt: Date;
  /** Duration of booking */
  duration: string;
};

export type RescheduleBookingResponse = {
  /** Id of created booking */
  id: string;
};

export type UpdateBookingRequestAllOf = {
  /** Booking ID */
  bookingId: string;
};

export type UpdateBookingRequest = BookingCommandDTO & UpdateBookingRequestAllOf;

export type UpdateBookingResponse = {
  /** ID of the updated booking */
  bookingId: string;
};

export type UpdateClientProfileRequestAllOf = {
  /** Client id */
  clientID: string;
};

export type UpdateClientProfileRequest = ClientCommandDTO & UpdateClientProfileRequestAllOf;

export type UpdateClientProfileResponse = {
  /** Id */
  id: string;
};

export type UpdateJobRequestAllOf = {
  /** Job ID */
  jobId: string;
};

export type UpdateJobRequest = JobCommandDTO & UpdateJobRequestAllOf;

export type UpdateJobResponse = {
  jobId: string;
};

export type UpdateMasterAvailabilityRequest = {
  /** Master identifier */
  masterId: string;
  /** Master availability identifier */
  masterAvailabilityId: string;
  availability: MasterAvailabilitySlotCommandDTO;
};

export type UpdateMasterAvailabilityResponse = {
  /** Master identifer */
  masterId: string;
  /** Master availability identifier */
  masterAvailabilityId: string;
};

export type UpdateMasterJobRequest = {
  masterId: string;
  masterJobId: string;
  job: MasterJobOfferingCommandDTO;
};

export type UpdateMasterJobResponse = {
  masterId?: string;
  masterJobId?: string;
};

export type UpdateMasterProfileRequestAllOf = {
  masterId: string;
};

export type UpdateMasterProfileRequest = MasterProfileCommandDTO & UpdateMasterProfileRequestAllOf;

export type UpdateMasterProfileResponse = {
  masterId?: string;
};

export type UploadClientProfileImageResponse = {
  /** Client id */
  clientId: string;
};

export type UploadMasterJobImageResponse = {
  masterId?: string;
  masterJobId?: string;
};

export type UploadMasterProfileImageResponse = {
  /** Master id */
  masterId: string;
};

export enum UserRole {
  Client = 'Client',
  Master = 'Master',

}
/**
 * @nullable
 */
export type ValidationProblemDetailsErrors = { [key: string]: string[] } | null;

export type ValidationProblemDetails = {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  errors?: ValidationProblemDetailsErrors;
  [key: string]: unknown;
};

export type FindBookingsParams = {
/**
 * Filter by master id
 */
  masterId?: string;
  /**
 * Filter by client id
 */
  clientId?: string;
  /**
 * Filter by status
 */
  status?: BookingStatus;
  /**
 * Filter by from
 */
  from?: Date;
  /**
 * Filter by to
 */
  to?: Date;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetBookingByIdParams = {
/**
 * Id
 */
  id: string;
};

export type FindClientsParams = {
/**
 * Filter by first name
 */
  firstName?: string;
  /**
 * Filter by last name
 */
  lastName?: string;
  /**
 * Filter by email address
 */
  email?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetClientByIdParams = {
  id?: string;
};

export type UploadClientProfileImageBody = {
  /** Client id */
  clientId: string;
  /** File uploads */
  files: Blob[];
};

export type FindJobsParams = {
/**
 * Filter by text
 */
  text?: string;
  /**
 * Filter by category
 */
  categoryId?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type FindJobCategoriesParams = {
/**
 * Filter by name
 */
  name?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetJobByIdParams = {
  id?: string;
};

export type FindMastersParams = {
  text?: string;
  city?: string;
  jobCategoryId?: string;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type GetMasterByIdParams = {
  id: string;
};

export type FindMasterAvailabilitiesParams = {
/**
 * Master identifier
 */
  masterId: string;
  /**
 * Filter by start date (slots starting on or after this date)
 */
  startAt?: Date;
  /**
 * Filter by end date (slots ending on or before this date)
 */
  endAt?: Date;
  /**
 * Page number
 */
  page?: number;
  /**
 * Items per page
 */
  pageSize?: number;
  /**
 * Sort by column
 */
  sortBy?: string;
  /**
 * Is sorting order ascending or descending, defaults to false (descending)
 */
  ascending?: boolean;
  /**
 * Retrieve all items
 */
  all?: boolean;
};

export type UploadMasterProfileImageBody = {
  /** Master id */
  masterId: string;
  /** File uploads */
  files: Blob[];
};

export type UploadMasterJobImageBody = {
  /** Master id */
  masterId: string;
  /** Master job id */
  masterJobId: string;
  /** File uploads */
  files: Blob[];
};
