/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {
  useMutation,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  ForgotPasswordRequest,
  LoginRequest,
  LoginResponse,
  ProblemDetails,
  RegisterUserRequest,
  ResetPasswordRequest,
  VerifyEmailParams,
} from './api.schemas';

/**
 * @summary Register user
 */
export const register = (
  registerUserRequest: RegisterUserRequest,
  signal?: AbortSignal,
) => customClient<void>(
  {
    url: '/api/v1/auth/register',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerUserRequest,
    signal,
  },
);

export const getRegisterMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError, { data: RegisterUserRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError, { data: RegisterUserRequest }, TContext> => {
  const mutationKey = ['register'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, { data: RegisterUserRequest }> = (props) => {
    const { data } = props ?? {};

    return register(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>;
export type RegisterMutationBody = RegisterUserRequest;
export type RegisterMutationError = ProblemDetails;

/**
 * @summary Register user
 */
export const useRegister = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError, { data: RegisterUserRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof register>>,
  TError,
  { data: RegisterUserRequest },
  TContext
  > => {
  const mutationOptions = getRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Login user
 */
export const login = (
  loginRequest: LoginRequest,
  signal?: AbortSignal,
) => customClient<LoginResponse>(
  {
    url: '/api/v1/auth/login',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginRequest,
    signal,
  },
);

export const getLoginMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginRequest }, TContext> => {
  const mutationKey = ['login'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, { data: LoginRequest }> = (props) => {
    const { data } = props ?? {};

    return login(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type LoginMutationBody = LoginRequest;
export type LoginMutationError = ProblemDetails;

/**
 * @summary Login user
 */
export const useLogin = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError, { data: LoginRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: LoginRequest },
  TContext
  > => {
  const mutationOptions = getLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Logout user
 */
export const logout = (

  signal?: AbortSignal,
) => customClient<void>(
  { url: '/api/v1/auth/logout', method: 'POST', signal },
);

export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext> => {
  const mutationKey = ['logout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => logout();

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>;

export type LogoutMutationError = unknown;

/**
 * @summary Logout user
 */
export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError, void, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  void,
  TContext
  > => {
  const mutationOptions = getLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Verify email address
 */
export const verifyEmail = (
  params?: VerifyEmailParams,
  signal?: AbortSignal,
) => customClient<unknown>(
  {
    url: '/api/v1/auth/verify-email',
    method: 'GET',
    params,
    signal,
  },
);

export const getVerifyEmailQueryKey = (params?: VerifyEmailParams) => ['/api/v1/auth/verify-email', ...(params ? [params] : [])] as const;

export const getVerifyEmailQueryOptions = <TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(params?: VerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVerifyEmailQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyEmail>>> = ({ signal }) => verifyEmail(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyEmailQueryResult = NonNullable<Awaited<ReturnType<typeof verifyEmail>>>;
export type VerifyEmailQueryError = void | ProblemDetails;

export function useVerifyEmail<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params: undefined | VerifyEmailParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof verifyEmail>>,
  TError,
  Awaited<ReturnType<typeof verifyEmail>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVerifyEmail<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params?: VerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof verifyEmail>>,
  TError,
  Awaited<ReturnType<typeof verifyEmail>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVerifyEmail<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params?: VerifyEmailParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Verify email address
 */

export function useVerifyEmail<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params?: VerifyEmailParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVerifyEmailQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getVerifyEmailSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(params?: VerifyEmailParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVerifyEmailQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof verifyEmail>>> = ({ signal }) => verifyEmail(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VerifyEmailSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof verifyEmail>>>;
export type VerifyEmailSuspenseQueryError = void | ProblemDetails;

export function useVerifyEmailSuspense<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params: undefined | VerifyEmailParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVerifyEmailSuspense<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params?: VerifyEmailParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVerifyEmailSuspense<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params?: VerifyEmailParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Verify email address
 */

export function useVerifyEmailSuspense<TData = Awaited<ReturnType<typeof verifyEmail>>, TError = void | ProblemDetails>(
  params?: VerifyEmailParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof verifyEmail>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVerifyEmailSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Forgot password
 */
export const forgotPassword = (
  forgotPasswordRequest: ForgotPasswordRequest,
  signal?: AbortSignal,
) => customClient<void>(
  {
    url: '/api/v1/auth/forgot-password',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: forgotPasswordRequest,
    signal,
  },
);

export const getForgotPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, { data: ForgotPasswordRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, { data: ForgotPasswordRequest }, TContext> => {
  const mutationKey = ['forgotPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof forgotPassword>>, { data: ForgotPasswordRequest }> = (props) => {
    const { data } = props ?? {};

    return forgotPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof forgotPassword>>>;
export type ForgotPasswordMutationBody = ForgotPasswordRequest;
export type ForgotPasswordMutationError = unknown;

/**
 * @summary Forgot password
 */
export const useForgotPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof forgotPassword>>, TError, { data: ForgotPasswordRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof forgotPassword>>,
  TError,
  { data: ForgotPasswordRequest },
  TContext
  > => {
  const mutationOptions = getForgotPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Reset password
 */
export const resetPassword = (
  resetPasswordRequest: ResetPasswordRequest,
  signal?: AbortSignal,
) => customClient<void>(
  {
    url: '/api/v1/auth/reset-password',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: resetPasswordRequest,
    signal,
  },
);

export const getResetPasswordMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError, { data: ResetPasswordRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError, { data: ResetPasswordRequest }, TContext> => {
  const mutationKey = ['resetPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, { data: ResetPasswordRequest }> = (props) => {
    const { data } = props ?? {};

    return resetPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>;
export type ResetPasswordMutationBody = ResetPasswordRequest;
export type ResetPasswordMutationError = ProblemDetails;

/**
 * @summary Reset password
 */
export const useResetPassword = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError, { data: ResetPasswordRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: ResetPasswordRequest },
  TContext
  > => {
  const mutationOptions = getResetPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
