/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {
  useMutation,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  ChangesetActionRequest,
  FindChangesetsParams,
  FindChangesetsResponsePagedResponse,
  GetPendingChangesetsCountResponse,
  ProblemDetails,
} from './api.schemas';

export const findChangesets = (
  params?: FindChangesetsParams,
  signal?: AbortSignal,
) => customClient<FindChangesetsResponsePagedResponse>(
  {
    url: '/api/v1/admin/changesets',
    method: 'GET',
    params,
    signal,
  },
);

export const getFindChangesetsQueryKey = (params?: FindChangesetsParams) => ['/api/v1/admin/changesets', ...(params ? [params] : [])] as const;

export const getFindChangesetsQueryOptions = <TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(params?: FindChangesetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindChangesetsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findChangesets>>> = ({ signal }) => findChangesets(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindChangesetsQueryResult = NonNullable<Awaited<ReturnType<typeof findChangesets>>>;
export type FindChangesetsQueryError = unknown;

export function useFindChangesets<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params: undefined | FindChangesetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findChangesets>>,
  TError,
  Awaited<ReturnType<typeof findChangesets>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindChangesets<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params?: FindChangesetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findChangesets>>,
  TError,
  Awaited<ReturnType<typeof findChangesets>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindChangesets<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params?: FindChangesetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFindChangesets<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params?: FindChangesetsParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindChangesetsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindChangesetsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(params?: FindChangesetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindChangesetsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findChangesets>>> = ({ signal }) => findChangesets(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindChangesetsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findChangesets>>>;
export type FindChangesetsSuspenseQueryError = unknown;

export function useFindChangesetsSuspense<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params: undefined | FindChangesetsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindChangesetsSuspense<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params?: FindChangesetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindChangesetsSuspense<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params?: FindChangesetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFindChangesetsSuspense<TData = Awaited<ReturnType<typeof findChangesets>>, TError = unknown>(
  params?: FindChangesetsParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findChangesets>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindChangesetsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getPendingChangesetsCount = (

  signal?: AbortSignal,
) => customClient<GetPendingChangesetsCountResponse>(
  { url: '/api/v1/admin/changesets/pending-count', method: 'GET', signal },
);

export const getGetPendingChangesetsCountQueryKey = () => ['/api/v1/admin/changesets/pending-count'] as const;

export const getGetPendingChangesetsCountQueryOptions = <TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPendingChangesetsCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPendingChangesetsCount>>> = ({ signal }) => getPendingChangesetsCount(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPendingChangesetsCountQueryResult = NonNullable<Awaited<ReturnType<typeof getPendingChangesetsCount>>>;
export type GetPendingChangesetsCountQueryError = unknown;

export function useGetPendingChangesetsCount<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getPendingChangesetsCount>>,
  TError,
  Awaited<ReturnType<typeof getPendingChangesetsCount>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPendingChangesetsCount<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getPendingChangesetsCount>>,
  TError,
  Awaited<ReturnType<typeof getPendingChangesetsCount>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPendingChangesetsCount<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPendingChangesetsCount<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPendingChangesetsCountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetPendingChangesetsCountSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPendingChangesetsCountQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPendingChangesetsCount>>> = ({ signal }) => getPendingChangesetsCount(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPendingChangesetsCountSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getPendingChangesetsCount>>>;
export type GetPendingChangesetsCountSuspenseQueryError = unknown;

export function useGetPendingChangesetsCountSuspense<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPendingChangesetsCountSuspense<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPendingChangesetsCountSuspense<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetPendingChangesetsCountSuspense<TData = Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError = unknown>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getPendingChangesetsCount>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPendingChangesetsCountSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const approveChangeset = (
  masterId: string,
  changesetId: string,
  changesetActionRequest: ChangesetActionRequest,
) => customClient<void>(
  {
    url: `/api/v1/admin/changesets/${masterId}/${changesetId}/approve`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: changesetActionRequest,
  },
);

export const getApproveChangesetMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveChangeset>>, TError, { masterId: string;changesetId: string;data: ChangesetActionRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof approveChangeset>>, TError, { masterId: string;changesetId: string;data: ChangesetActionRequest }, TContext> => {
  const mutationKey = ['approveChangeset'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof approveChangeset>>, { masterId: string;changesetId: string;data: ChangesetActionRequest }> = (props) => {
    const { masterId, changesetId, data } = props ?? {};

    return approveChangeset(masterId, changesetId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApproveChangesetMutationResult = NonNullable<Awaited<ReturnType<typeof approveChangeset>>>;
export type ApproveChangesetMutationBody = ChangesetActionRequest;
export type ApproveChangesetMutationError = ProblemDetails;

export const useApproveChangeset = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof approveChangeset>>, TError, { masterId: string;changesetId: string;data: ChangesetActionRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof approveChangeset>>,
  TError,
  { masterId: string;changesetId: string;data: ChangesetActionRequest },
  TContext
  > => {
  const mutationOptions = getApproveChangesetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const rejectChangeset = (
  masterId: string,
  changesetId: string,
  changesetActionRequest: ChangesetActionRequest,
) => customClient<void>(
  {
    url: `/api/v1/admin/changesets/${masterId}/${changesetId}/reject`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: changesetActionRequest,
  },
);

export const getRejectChangesetMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectChangeset>>, TError, { masterId: string;changesetId: string;data: ChangesetActionRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof rejectChangeset>>, TError, { masterId: string;changesetId: string;data: ChangesetActionRequest }, TContext> => {
  const mutationKey = ['rejectChangeset'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof rejectChangeset>>, { masterId: string;changesetId: string;data: ChangesetActionRequest }> = (props) => {
    const { masterId, changesetId, data } = props ?? {};

    return rejectChangeset(masterId, changesetId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type RejectChangesetMutationResult = NonNullable<Awaited<ReturnType<typeof rejectChangeset>>>;
export type RejectChangesetMutationBody = ChangesetActionRequest;
export type RejectChangesetMutationError = ProblemDetails;

export const useRejectChangeset = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rejectChangeset>>, TError, { masterId: string;changesetId: string;data: ChangesetActionRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof rejectChangeset>>,
  TError,
  { masterId: string;changesetId: string;data: ChangesetActionRequest },
  TContext
  > => {
  const mutationOptions = getRejectChangesetMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
