/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';
import {
  useMutation,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  DiditWebhookPayload,
} from './api.schemas';

/**
 * @summary Receive Didit verification status webhook
 */
export const diditWebhook = (
  diditWebhookPayload: DiditWebhookPayload,
  signal?: AbortSignal,
) => customClient<void>(
  {
    url: '/api/v1/webhooks/didit',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: diditWebhookPayload,
    signal,
  },
);

export const getDiditWebhookMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof diditWebhook>>, TError, { data: DiditWebhookPayload }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof diditWebhook>>, TError, { data: DiditWebhookPayload }, TContext> => {
  const mutationKey = ['diditWebhook'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof diditWebhook>>, { data: DiditWebhookPayload }> = (props) => {
    const { data } = props ?? {};

    return diditWebhook(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiditWebhookMutationResult = NonNullable<Awaited<ReturnType<typeof diditWebhook>>>;
export type DiditWebhookMutationBody = DiditWebhookPayload;
export type DiditWebhookMutationError = unknown;

/**
 * @summary Receive Didit verification status webhook
 */
export const useDiditWebhook = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof diditWebhook>>, TError, { data: DiditWebhookPayload }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof diditWebhook>>,
  TError,
  { data: DiditWebhookPayload },
  TContext
  > => {
  const mutationOptions = getDiditWebhookMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
