/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  CreateJobRequest,
  CreateJobResponse,
  FindJobsParams,
  FindJobsResponsePagedResponse,
  GetJobByIdParams,
  GetJobByIdResponse,
  ProblemDetails,
  UpdateJobRequest,
  UpdateJobResponse,
  ValidationProblemDetails,
} from './api.schemas';

/**
 * @summary Find jobs
 */
export const findJobs = (
  params?: FindJobsParams,
  signal?: AbortSignal,
) => customClient<FindJobsResponsePagedResponse>(
  {
    url: '/api/v1/jobs',
    method: 'GET',
    params,
    signal,
  },
);

export const getFindJobsQueryKey = (params?: FindJobsParams) => ['/api/v1/jobs', ...(params ? [params] : [])] as const;

export const getFindJobsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof findJobs>>, FindJobsParams['page']>, TError = ValidationProblemDetails>(params?: FindJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData, QueryKey, FindJobsParams['page']>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindJobsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findJobs>>, QueryKey, FindJobsParams['page']> = ({ signal, pageParam }) => findJobs({ ...params, page: pageParam || params?.page }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData, QueryKey, FindJobsParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindJobsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof findJobs>>>;
export type FindJobsInfiniteQueryError = ValidationProblemDetails;

export function useFindJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findJobs>>, FindJobsParams['page']>, TError = ValidationProblemDetails>(
  params: undefined | FindJobsParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData, QueryKey, FindJobsParams['page']>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findJobs>>,
  TError,
  Awaited<ReturnType<typeof findJobs>>, QueryKey
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findJobs>>, FindJobsParams['page']>, TError = ValidationProblemDetails>(
  params?: FindJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData, QueryKey, FindJobsParams['page']>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findJobs>>,
  TError,
  Awaited<ReturnType<typeof findJobs>>, QueryKey
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findJobs>>, FindJobsParams['page']>, TError = ValidationProblemDetails>(
  params?: FindJobsParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData, QueryKey, FindJobsParams['page']>>, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find jobs
 */

export function useFindJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findJobs>>, FindJobsParams['page']>, TError = ValidationProblemDetails>(
  params?: FindJobsParams,
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData, QueryKey, FindJobsParams['page']>>, },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindJobsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindJobsQueryOptions = <TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(params?: FindJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindJobsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findJobs>>> = ({ signal }) => findJobs(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindJobsQueryResult = NonNullable<Awaited<ReturnType<typeof findJobs>>>;
export type FindJobsQueryError = ValidationProblemDetails;

export function useFindJobs<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params: undefined | FindJobsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findJobs>>,
  TError,
  Awaited<ReturnType<typeof findJobs>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindJobs<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params?: FindJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findJobs>>,
  TError,
  Awaited<ReturnType<typeof findJobs>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindJobs<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params?: FindJobsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find jobs
 */

export function useFindJobs<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params?: FindJobsParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindJobsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindJobsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(params?: FindJobsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindJobsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findJobs>>> = ({ signal }) => findJobs(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindJobsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findJobs>>>;
export type FindJobsSuspenseQueryError = ValidationProblemDetails;

export function useFindJobsSuspense<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params: undefined | FindJobsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindJobsSuspense<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params?: FindJobsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindJobsSuspense<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params?: FindJobsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find jobs
 */

export function useFindJobsSuspense<TData = Awaited<ReturnType<typeof findJobs>>, TError = ValidationProblemDetails>(
  params?: FindJobsParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findJobs>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindJobsSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a job
 */
export const createJob = (
  createJobRequest: CreateJobRequest,
  signal?: AbortSignal,
) => customClient<CreateJobResponse>(
  {
    url: '/api/v1/jobs',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createJobRequest,
    signal,
  },
);

export const getCreateJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError, { data: CreateJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError, { data: CreateJobRequest }, TContext> => {
  const mutationKey = ['createJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createJob>>, { data: CreateJobRequest }> = (props) => {
    const { data } = props ?? {};

    return createJob(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateJobMutationResult = NonNullable<Awaited<ReturnType<typeof createJob>>>;
export type CreateJobMutationBody = CreateJobRequest;
export type CreateJobMutationError = ProblemDetails | ValidationProblemDetails;

/**
 * @summary Create a job
 */
export const useCreateJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createJob>>, TError, { data: CreateJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof createJob>>,
  TError,
  { data: CreateJobRequest },
  TContext
  > => {
  const mutationOptions = getCreateJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get job by id
 */
export const getJobById = (
  id: string,
  params?: GetJobByIdParams,
  signal?: AbortSignal,
) => customClient<GetJobByIdResponse>(
  {
    url: `/api/v1/jobs/${id}`,
    method: 'GET',
    params,
    signal,
  },
);

export const getGetJobByIdQueryKey = (
  id?: string,
  params?: GetJobByIdParams,
) => [`/api/v1/jobs/${id}`, ...(params ? [params] : [])] as const;

export const getGetJobByIdQueryOptions = <TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(id: string,
  params?: GetJobByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJobByIdQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobById>>> = ({ signal }) => getJobById(id, params, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetJobByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getJobById>>>;
export type GetJobByIdQueryError = ProblemDetails;

export function useGetJobById<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params: undefined | GetJobByIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getJobById>>,
  TError,
  Awaited<ReturnType<typeof getJobById>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetJobById<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params?: GetJobByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getJobById>>,
  TError,
  Awaited<ReturnType<typeof getJobById>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetJobById<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params?: GetJobByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get job by id
 */

export function useGetJobById<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params?: GetJobByIdParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetJobByIdQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetJobByIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(id: string,
  params?: GetJobByIdParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetJobByIdQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getJobById>>> = ({ signal }) => getJobById(id, params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetJobByIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getJobById>>>;
export type GetJobByIdSuspenseQueryError = ProblemDetails;

export function useGetJobByIdSuspense<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params: undefined | GetJobByIdParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetJobByIdSuspense<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params?: GetJobByIdParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetJobByIdSuspense<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params?: GetJobByIdParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get job by id
 */

export function useGetJobByIdSuspense<TData = Awaited<ReturnType<typeof getJobById>>, TError = ProblemDetails>(
  id: string,
  params?: GetJobByIdParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getJobById>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetJobByIdSuspenseQueryOptions(id, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update job
 */
export const updateJob = (
  id: string,
  updateJobRequest: UpdateJobRequest,
) => customClient<UpdateJobResponse>(
  {
    url: `/api/v1/jobs/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateJobRequest,
  },
);

export const getUpdateJobMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext> => {
  const mutationKey = ['updateJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateJob>>, { id: string;data: UpdateJobRequest }> = (props) => {
    const { id, data } = props ?? {};

    return updateJob(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateJobMutationResult = NonNullable<Awaited<ReturnType<typeof updateJob>>>;
export type UpdateJobMutationBody = UpdateJobRequest;
export type UpdateJobMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Update job
 */
export const useUpdateJob = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateJob>>, TError, { id: string;data: UpdateJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof updateJob>>,
  TError,
  { id: string;data: UpdateJobRequest },
  TContext
  > => {
  const mutationOptions = getUpdateJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
