/* eslint-disable no-nested-ternary */
/**
 * Generated by orval
 * Do not edit manually.
 * Beautify Baltics Core API
 * Beautify Baltics Core API for back-office operations
 * OpenAPI spec version: v1
 */
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';

import { customClient } from '../mutator/custom-client';

import type {
  CreateMasterAvailabilityRequest,
  CreateMasterAvailabilityResponse,
  CreateMasterJobRequest,
  CreateMasterJobResponse,
  CreateMasterRequest,
  CreateMasterResponse,
  FindMasterAvailabilitiesParams,
  FindMasterAvailabilitiesResponsePagedResponse,
  FindMasterJobImagesResponse,
  FindMasterJobsResponse,
  FindMastersParams,
  FindMastersResponsePagedResponse,
  GetMasterAvailabilityResponse,
  GetMasterByIdParams,
  GetMasterByIdResponse,
  GetMasterJobImageByIdResponse,
  ProblemDetails,
  UpdateMasterAvailabilityRequest,
  UpdateMasterAvailabilityResponse,
  UpdateMasterJobRequest,
  UpdateMasterJobResponse,
  UpdateMasterProfileRequest,
  UpdateMasterProfileResponse,
  UploadMasterJobImageBody,
  UploadMasterJobImageResponse,
  UploadMasterProfileImageBody,
  UploadMasterProfileImageResponse,
  ValidationProblemDetails,
} from './api.schemas';

/**
 * @summary Find masters
 */
export const findMasters = (
  params?: FindMastersParams,
  signal?: AbortSignal,
) => customClient<FindMastersResponsePagedResponse>(
  {
    url: '/api/v1/masters',
    method: 'GET',
    params,
    signal,
  },
);

export const getFindMastersQueryKey = (params?: FindMastersParams) => ['/api/v1/masters', ...(params ? [params] : [])] as const;

export const getFindMastersInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof findMasters>>, FindMastersParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(params?: FindMastersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData, QueryKey, FindMastersParams['page']>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMastersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasters>>, QueryKey, FindMastersParams['page']> = ({ signal, pageParam }) => findMasters({ ...params, page: pageParam || params?.page }, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData, QueryKey, FindMastersParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMastersInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof findMasters>>>;
export type FindMastersInfiniteQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMastersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasters>>, FindMastersParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  params: undefined | FindMastersParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData, QueryKey, FindMastersParams['page']>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasters>>,
  TError,
  Awaited<ReturnType<typeof findMasters>>, QueryKey
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMastersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasters>>, FindMastersParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData, QueryKey, FindMastersParams['page']>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasters>>,
  TError,
  Awaited<ReturnType<typeof findMasters>>, QueryKey
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMastersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasters>>, FindMastersParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData, QueryKey, FindMastersParams['page']>>, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find masters
 */

export function useFindMastersInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasters>>, FindMastersParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams,
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData, QueryKey, FindMastersParams['page']>>, },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMastersInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMastersQueryOptions = <TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(params?: FindMastersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMastersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasters>>> = ({ signal }) => findMasters(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMastersQueryResult = NonNullable<Awaited<ReturnType<typeof findMasters>>>;
export type FindMastersQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasters<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params: undefined | FindMastersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasters>>,
  TError,
  Awaited<ReturnType<typeof findMasters>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasters<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasters>>,
  TError,
  Awaited<ReturnType<typeof findMasters>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasters<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find masters
 */

export function useFindMasters<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMastersQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMastersSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(params?: FindMastersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMastersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasters>>> = ({ signal }) => findMasters(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMastersSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findMasters>>>;
export type FindMastersSuspenseQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMastersSuspense<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params: undefined | FindMastersParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMastersSuspense<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMastersSuspense<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find masters
 */

export function useFindMastersSuspense<TData = Awaited<ReturnType<typeof findMasters>>, TError = ProblemDetails | ValidationProblemDetails>(
  params?: FindMastersParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasters>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMastersSuspenseQueryOptions(params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create master
 */
export const createMaster = (
  createMasterRequest: CreateMasterRequest,
  signal?: AbortSignal,
) => customClient<CreateMasterResponse>(
  {
    url: '/api/v1/masters',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createMasterRequest,
    signal,
  },
);

export const getCreateMasterMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMaster>>, TError, { data: CreateMasterRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof createMaster>>, TError, { data: CreateMasterRequest }, TContext> => {
  const mutationKey = ['createMaster'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMaster>>, { data: CreateMasterRequest }> = (props) => {
    const { data } = props ?? {};

    return createMaster(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMasterMutationResult = NonNullable<Awaited<ReturnType<typeof createMaster>>>;
export type CreateMasterMutationBody = CreateMasterRequest;
export type CreateMasterMutationError = ProblemDetails | ValidationProblemDetails;

/**
 * @summary Create master
 */
export const useCreateMaster = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMaster>>, TError, { data: CreateMasterRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof createMaster>>,
  TError,
  { data: CreateMasterRequest },
  TContext
  > => {
  const mutationOptions = getCreateMasterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get a master by id
 */
export const getMasterById = (
  id: string,
  params: GetMasterByIdParams,
  signal?: AbortSignal,
) => customClient<GetMasterByIdResponse>(
  {
    url: `/api/v1/masters/${id}`,
    method: 'GET',
    params,
    signal,
  },
);

export const getGetMasterByIdQueryKey = (
  id?: string,
  params?: GetMasterByIdParams,
) => [`/api/v1/masters/${id}`, ...(params ? [params] : [])] as const;

export const getGetMasterByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(id: string,
  params: GetMasterByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterByIdQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterById>>> = ({ signal }) => getMasterById(id, params, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterById>>>;
export type GetMasterByIdQueryError = ProblemDetails;

export function useGetMasterById<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterById>>,
  TError,
  Awaited<ReturnType<typeof getMasterById>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterById<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterById>>,
  TError,
  Awaited<ReturnType<typeof getMasterById>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterById<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a master by id
 */

export function useGetMasterById<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterByIdQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMasterByIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(id: string,
  params: GetMasterByIdParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterByIdQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterById>>> = ({ signal }) => getMasterById(id, params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterByIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterById>>>;
export type GetMasterByIdSuspenseQueryError = ProblemDetails;

export function useGetMasterByIdSuspense<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterByIdSuspense<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterByIdSuspense<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get a master by id
 */

export function useGetMasterByIdSuspense<TData = Awaited<ReturnType<typeof getMasterById>>, TError = ProblemDetails>(
  id: string,
  params: GetMasterByIdParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterById>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterByIdSuspenseQueryOptions(id, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update master profile
 */
export const updateMasterProfile = (
  id: string,
  updateMasterProfileRequest: UpdateMasterProfileRequest,
) => customClient<UpdateMasterProfileResponse>(
  {
    url: `/api/v1/masters/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateMasterProfileRequest,
  },
);

export const getUpdateMasterProfileMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMasterProfile>>, TError, { id: string;data: UpdateMasterProfileRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof updateMasterProfile>>, TError, { id: string;data: UpdateMasterProfileRequest }, TContext> => {
  const mutationKey = ['updateMasterProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMasterProfile>>, { id: string;data: UpdateMasterProfileRequest }> = (props) => {
    const { id, data } = props ?? {};

    return updateMasterProfile(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMasterProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateMasterProfile>>>;
export type UpdateMasterProfileMutationBody = UpdateMasterProfileRequest;
export type UpdateMasterProfileMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Update master profile
 */
export const useUpdateMasterProfile = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMasterProfile>>, TError, { id: string;data: UpdateMasterProfileRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof updateMasterProfile>>,
  TError,
  { id: string;data: UpdateMasterProfileRequest },
  TContext
  > => {
  const mutationOptions = getUpdateMasterProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create a master job
 */
export const createMasterJob = (
  id: string,
  createMasterJobRequest: CreateMasterJobRequest,
  signal?: AbortSignal,
) => customClient<CreateMasterJobResponse>(
  {
    url: `/api/v1/masters/${id}/jobs`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createMasterJobRequest,
    signal,
  },
);

export const getCreateMasterJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMasterJob>>, TError, { id: string;data: CreateMasterJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof createMasterJob>>, TError, { id: string;data: CreateMasterJobRequest }, TContext> => {
  const mutationKey = ['createMasterJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMasterJob>>, { id: string;data: CreateMasterJobRequest }> = (props) => {
    const { id, data } = props ?? {};

    return createMasterJob(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMasterJobMutationResult = NonNullable<Awaited<ReturnType<typeof createMasterJob>>>;
export type CreateMasterJobMutationBody = CreateMasterJobRequest;
export type CreateMasterJobMutationError = ProblemDetails | ValidationProblemDetails;

/**
 * @summary Create a master job
 */
export const useCreateMasterJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMasterJob>>, TError, { id: string;data: CreateMasterJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof createMasterJob>>,
  TError,
  { id: string;data: CreateMasterJobRequest },
  TContext
  > => {
  const mutationOptions = getCreateMasterJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Find master jobs
 */
export const findMasterJobs = (
  id: string,
  signal?: AbortSignal,
) => customClient<FindMasterJobsResponse>(
  { url: `/api/v1/masters/${id}/jobs`, method: 'GET', signal },
);

export const getFindMasterJobsQueryKey = (id?: string) => [`/api/v1/masters/${id}/jobs`] as const;

export const getFindMasterJobsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobs>>>, TError = ProblemDetails | ValidationProblemDetails>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterJobsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterJobs>>> = ({ signal }) => findMasterJobs(id, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterJobsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterJobs>>>;
export type FindMasterJobsInfiniteQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasterJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobs>>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobs>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobs>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobs>>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobs>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobs>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobs>>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find master jobs
 */

export function useFindMasterJobsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobs>>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterJobsInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMasterJobsQueryOptions = <TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterJobsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterJobs>>> = ({ signal }) => findMasterJobs(id, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterJobsQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterJobs>>>;
export type FindMasterJobsQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasterJobs<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobs>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobs>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobs<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobs>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobs>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobs<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find master jobs
 */

export function useFindMasterJobs<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterJobsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMasterJobsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterJobsQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterJobs>>> = ({ signal }) => findMasterJobs(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterJobsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterJobs>>>;
export type FindMasterJobsSuspenseQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasterJobsSuspense<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobsSuspense<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobsSuspense<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find master jobs
 */

export function useFindMasterJobsSuspense<TData = Awaited<ReturnType<typeof findMasterJobs>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobs>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterJobsSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Find all images for a master's jobs
 */
export const findMasterJobImages = (
  id: string,
  signal?: AbortSignal,
) => customClient<FindMasterJobImagesResponse>(
  { url: `/api/v1/masters/${id}/images`, method: 'GET', signal },
);

export const getFindMasterJobImagesQueryKey = (id?: string) => [`/api/v1/masters/${id}/images`] as const;

export const getFindMasterJobImagesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobImages>>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterJobImagesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterJobImages>>> = ({ signal }) => findMasterJobImages(id, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterJobImagesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterJobImages>>>;
export type FindMasterJobImagesInfiniteQueryError = ProblemDetails;

export function useFindMasterJobImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobImages>>>, TError = ProblemDetails>(
  id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobImages>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobImages>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobImages>>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobImages>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobImages>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobImages>>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find all images for a master's jobs
 */

export function useFindMasterJobImagesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterJobImages>>>, TError = ProblemDetails>(
  id: string,
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterJobImagesInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMasterJobImagesQueryOptions = <TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterJobImagesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterJobImages>>> = ({ signal }) => findMasterJobImages(id, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterJobImagesQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterJobImages>>>;
export type FindMasterJobImagesQueryError = ProblemDetails;

export function useFindMasterJobImages<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobImages>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobImages>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobImages<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterJobImages>>,
  TError,
  Awaited<ReturnType<typeof findMasterJobImages>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobImages<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find all images for a master's jobs
 */

export function useFindMasterJobImages<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterJobImagesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMasterJobImagesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterJobImagesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterJobImages>>> = ({ signal }) => findMasterJobImages(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterJobImagesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterJobImages>>>;
export type FindMasterJobImagesSuspenseQueryError = ProblemDetails;

export function useFindMasterJobImagesSuspense<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobImagesSuspense<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterJobImagesSuspense<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find all images for a master's jobs
 */

export function useFindMasterJobImagesSuspense<TData = Awaited<ReturnType<typeof findMasterJobImages>>, TError = ProblemDetails>(
  id: string,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterJobImages>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterJobImagesSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete master job
 */
export const deleteMasterJob = (
  id: string,
  jobId: string,
) => customClient<void>(
  { url: `/api/v1/masters/${id}/jobs/${jobId}`, method: 'DELETE' },
);

export const getDeleteMasterJobMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMasterJob>>, TError, { id: string;jobId: string }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof deleteMasterJob>>, TError, { id: string;jobId: string }, TContext> => {
  const mutationKey = ['deleteMasterJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMasterJob>>, { id: string;jobId: string }> = (props) => {
    const { id, jobId } = props ?? {};

    return deleteMasterJob(id, jobId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMasterJobMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMasterJob>>>;

export type DeleteMasterJobMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Delete master job
 */
export const useDeleteMasterJob = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMasterJob>>, TError, { id: string;jobId: string }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof deleteMasterJob>>,
  TError,
  { id: string;jobId: string },
  TContext
  > => {
  const mutationOptions = getDeleteMasterJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update master job
 */
export const updateMasterJob = (
  id: string,
  jobId: string,
  updateMasterJobRequest: UpdateMasterJobRequest,
) => customClient<UpdateMasterJobResponse>(
  {
    url: `/api/v1/masters/${id}/jobs/${jobId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateMasterJobRequest,
  },
);

export const getUpdateMasterJobMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMasterJob>>, TError, { id: string;jobId: string;data: UpdateMasterJobRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof updateMasterJob>>, TError, { id: string;jobId: string;data: UpdateMasterJobRequest }, TContext> => {
  const mutationKey = ['updateMasterJob'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMasterJob>>, { id: string;jobId: string;data: UpdateMasterJobRequest }> = (props) => {
    const { id, jobId, data } = props ?? {};

    return updateMasterJob(id, jobId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMasterJobMutationResult = NonNullable<Awaited<ReturnType<typeof updateMasterJob>>>;
export type UpdateMasterJobMutationBody = UpdateMasterJobRequest;
export type UpdateMasterJobMutationError = ProblemDetails | ValidationProblemDetails;

/**
 * @summary Update master job
 */
export const useUpdateMasterJob = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMasterJob>>, TError, { id: string;jobId: string;data: UpdateMasterJobRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof updateMasterJob>>,
  TError,
  { id: string;jobId: string;data: UpdateMasterJobRequest },
  TContext
  > => {
  const mutationOptions = getUpdateMasterJobMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Create master availability
 */
export const createMasterAvailability = (
  id: string,
  createMasterAvailabilityRequest: CreateMasterAvailabilityRequest,
  signal?: AbortSignal,
) => customClient<CreateMasterAvailabilityResponse>(
  {
    url: `/api/v1/masters/${id}/availability`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createMasterAvailabilityRequest,
    signal,
  },
);

export const getCreateMasterAvailabilityMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMasterAvailability>>, TError, { id: string;data: CreateMasterAvailabilityRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof createMasterAvailability>>, TError, { id: string;data: CreateMasterAvailabilityRequest }, TContext> => {
  const mutationKey = ['createMasterAvailability'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMasterAvailability>>, { id: string;data: CreateMasterAvailabilityRequest }> = (props) => {
    const { id, data } = props ?? {};

    return createMasterAvailability(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMasterAvailabilityMutationResult = NonNullable<Awaited<ReturnType<typeof createMasterAvailability>>>;
export type CreateMasterAvailabilityMutationBody = CreateMasterAvailabilityRequest;
export type CreateMasterAvailabilityMutationError = ProblemDetails | ValidationProblemDetails;

/**
 * @summary Create master availability
 */
export const useCreateMasterAvailability = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMasterAvailability>>, TError, { id: string;data: CreateMasterAvailabilityRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof createMasterAvailability>>,
  TError,
  { id: string;data: CreateMasterAvailabilityRequest },
  TContext
  > => {
  const mutationOptions = getCreateMasterAvailabilityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Find master availabilities
 */
export const findMasterAvailabilities = (
  id: string,
  params: FindMasterAvailabilitiesParams,
  signal?: AbortSignal,
) => customClient<FindMasterAvailabilitiesResponsePagedResponse>(
  {
    url: `/api/v1/masters/${id}/availability`,
    method: 'GET',
    params,
    signal,
  },
);

export const getFindMasterAvailabilitiesQueryKey = (
  id?: string,
  params?: FindMasterAvailabilitiesParams,
) => [`/api/v1/masters/${id}/availability`, ...(params ? [params] : [])] as const;

export const getFindMasterAvailabilitiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof findMasterAvailabilities>>, FindMasterAvailabilitiesParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData, QueryKey, FindMasterAvailabilitiesParams['page']>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterAvailabilitiesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterAvailabilities>>, QueryKey, FindMasterAvailabilitiesParams['page']> = ({ signal, pageParam }) => findMasterAvailabilities(id, { ...params, page: pageParam || params?.page }, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData, QueryKey, FindMasterAvailabilitiesParams['page']> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterAvailabilitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterAvailabilities>>>;
export type FindMasterAvailabilitiesInfiniteQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasterAvailabilitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterAvailabilities>>, FindMasterAvailabilitiesParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData, QueryKey, FindMasterAvailabilitiesParams['page']>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterAvailabilities>>,
  TError,
  Awaited<ReturnType<typeof findMasterAvailabilities>>, QueryKey
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterAvailabilitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterAvailabilities>>, FindMasterAvailabilitiesParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData, QueryKey, FindMasterAvailabilitiesParams['page']>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterAvailabilities>>,
  TError,
  Awaited<ReturnType<typeof findMasterAvailabilities>>, QueryKey
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterAvailabilitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterAvailabilities>>, FindMasterAvailabilitiesParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData, QueryKey, FindMasterAvailabilitiesParams['page']>>, }
  , queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find master availabilities
 */

export function useFindMasterAvailabilitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof findMasterAvailabilities>>, FindMasterAvailabilitiesParams['page']>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams,
  options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData, QueryKey, FindMasterAvailabilitiesParams['page']>>, },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterAvailabilitiesInfiniteQueryOptions(id, params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMasterAvailabilitiesQueryOptions = <TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterAvailabilitiesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterAvailabilities>>> = ({ signal }) => findMasterAvailabilities(id, params, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterAvailabilitiesQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterAvailabilities>>>;
export type FindMasterAvailabilitiesQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasterAvailabilities<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterAvailabilities>>,
  TError,
  Awaited<ReturnType<typeof findMasterAvailabilities>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterAvailabilities<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof findMasterAvailabilities>>,
  TError,
  Awaited<ReturnType<typeof findMasterAvailabilities>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterAvailabilities<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find master availabilities
 */

export function useFindMasterAvailabilities<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterAvailabilitiesQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getFindMasterAvailabilitiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindMasterAvailabilitiesQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findMasterAvailabilities>>> = ({ signal }) => findMasterAvailabilities(id, params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FindMasterAvailabilitiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof findMasterAvailabilities>>>;
export type FindMasterAvailabilitiesSuspenseQueryError = ProblemDetails | ValidationProblemDetails;

export function useFindMasterAvailabilitiesSuspense<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterAvailabilitiesSuspense<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFindMasterAvailabilitiesSuspense<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Find master availabilities
 */

export function useFindMasterAvailabilitiesSuspense<TData = Awaited<ReturnType<typeof findMasterAvailabilities>>, TError = ProblemDetails | ValidationProblemDetails>(
  id: string,
  params: FindMasterAvailabilitiesParams,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof findMasterAvailabilities>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindMasterAvailabilitiesSuspenseQueryOptions(id, params, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update master availability
 */
export const updateMasterAvailability = (
  id: string,
  availabilityId: string,
  updateMasterAvailabilityRequest: UpdateMasterAvailabilityRequest,
) => customClient<UpdateMasterAvailabilityResponse>(
  {
    url: `/api/v1/masters/${id}/availability/${availabilityId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateMasterAvailabilityRequest,
  },
);

export const getUpdateMasterAvailabilityMutationOptions = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMasterAvailability>>, TError, { id: string;availabilityId: string;data: UpdateMasterAvailabilityRequest }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof updateMasterAvailability>>, TError, { id: string;availabilityId: string;data: UpdateMasterAvailabilityRequest }, TContext> => {
  const mutationKey = ['updateMasterAvailability'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMasterAvailability>>, { id: string;availabilityId: string;data: UpdateMasterAvailabilityRequest }> = (props) => {
    const { id, availabilityId, data } = props ?? {};

    return updateMasterAvailability(id, availabilityId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMasterAvailabilityMutationResult = NonNullable<Awaited<ReturnType<typeof updateMasterAvailability>>>;
export type UpdateMasterAvailabilityMutationBody = UpdateMasterAvailabilityRequest;
export type UpdateMasterAvailabilityMutationError = ProblemDetails | ValidationProblemDetails;

/**
 * @summary Update master availability
 */
export const useUpdateMasterAvailability = <TError = ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMasterAvailability>>, TError, { id: string;availabilityId: string;data: UpdateMasterAvailabilityRequest }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof updateMasterAvailability>>,
  TError,
  { id: string;availabilityId: string;data: UpdateMasterAvailabilityRequest },
  TContext
  > => {
  const mutationOptions = getUpdateMasterAvailabilityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get master availability by id
 */
export const getMasterAvailability = (
  id: string,
  availabilityId: string,
  signal?: AbortSignal,
) => customClient<GetMasterAvailabilityResponse>(
  { url: `/api/v1/masters/${id}/availability/${availabilityId}`, method: 'GET', signal },
);

export const getGetMasterAvailabilityQueryKey = (
  id?: string,
  availabilityId?: string,
) => [`/api/v1/masters/${id}/availability/${availabilityId}`] as const;

export const getGetMasterAvailabilityQueryOptions = <TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(id: string,
  availabilityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterAvailabilityQueryKey(id, availabilityId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterAvailability>>> = ({ signal }) => getMasterAvailability(id, availabilityId, signal);

  return {
    queryKey, queryFn, enabled: !!(id && availabilityId), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterAvailabilityQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterAvailability>>>;
export type GetMasterAvailabilityQueryError = ProblemDetails;

export function useGetMasterAvailability<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterAvailability>>,
  TError,
  Awaited<ReturnType<typeof getMasterAvailability>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterAvailability<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterAvailability>>,
  TError,
  Awaited<ReturnType<typeof getMasterAvailability>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterAvailability<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get master availability by id
 */

export function useGetMasterAvailability<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterAvailabilityQueryOptions(id, availabilityId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMasterAvailabilitySuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(id: string,
  availabilityId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterAvailabilityQueryKey(id, availabilityId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterAvailability>>> = ({ signal }) => getMasterAvailability(id, availabilityId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterAvailabilitySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterAvailability>>>;
export type GetMasterAvailabilitySuspenseQueryError = ProblemDetails;

export function useGetMasterAvailabilitySuspense<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterAvailabilitySuspense<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterAvailabilitySuspense<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get master availability by id
 */

export function useGetMasterAvailabilitySuspense<TData = Awaited<ReturnType<typeof getMasterAvailability>>, TError = ProblemDetails>(
  id: string,
  availabilityId: string,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterAvailability>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterAvailabilitySuspenseQueryOptions(id, availabilityId, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete master availability
 */
export const deleteMasterAvailability = (
  id: string,
  availabilityId: string,
) => customClient<void>(
  { url: `/api/v1/masters/${id}/availability/${availabilityId}`, method: 'DELETE' },
);

export const getDeleteMasterAvailabilityMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMasterAvailability>>, TError, { id: string;availabilityId: string }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof deleteMasterAvailability>>, TError, { id: string;availabilityId: string }, TContext> => {
  const mutationKey = ['deleteMasterAvailability'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMasterAvailability>>, { id: string;availabilityId: string }> = (props) => {
    const { id, availabilityId } = props ?? {};

    return deleteMasterAvailability(id, availabilityId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMasterAvailabilityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMasterAvailability>>>;

export type DeleteMasterAvailabilityMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Delete master availability
 */
export const useDeleteMasterAvailability = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMasterAvailability>>, TError, { id: string;availabilityId: string }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof deleteMasterAvailability>>,
  TError,
  { id: string;availabilityId: string },
  TContext
  > => {
  const mutationOptions = getDeleteMasterAvailabilityMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Upload master profile image
 */
export const uploadMasterProfileImage = (
  id: string,
  uploadMasterProfileImageBody: UploadMasterProfileImageBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append('masterId', uploadMasterProfileImageBody.masterId);
  uploadMasterProfileImageBody.files.forEach((value) => formData.append('files', value));

  return customClient<UploadMasterProfileImageResponse>(
    {
      url: `/api/v1/masters/${id}/profile-image`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
  );
};

export const getUploadMasterProfileImageMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadMasterProfileImage>>, TError, { id: string;data: UploadMasterProfileImageBody }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof uploadMasterProfileImage>>, TError, { id: string;data: UploadMasterProfileImageBody }, TContext> => {
  const mutationKey = ['uploadMasterProfileImage'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadMasterProfileImage>>, { id: string;data: UploadMasterProfileImageBody }> = (props) => {
    const { id, data } = props ?? {};

    return uploadMasterProfileImage(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMasterProfileImageMutationResult = NonNullable<Awaited<ReturnType<typeof uploadMasterProfileImage>>>;
export type UploadMasterProfileImageMutationBody = UploadMasterProfileImageBody;
export type UploadMasterProfileImageMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Upload master profile image
 */
export const useUploadMasterProfileImage = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadMasterProfileImage>>, TError, { id: string;data: UploadMasterProfileImageBody }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof uploadMasterProfileImage>>,
  TError,
  { id: string;data: UploadMasterProfileImageBody },
  TContext
  > => {
  const mutationOptions = getUploadMasterProfileImageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get master profile image
 */
export const getMasterProfileImage = (
  id: string,
  signal?: AbortSignal,
) => customClient<Blob>(
  {
    url: `/api/v1/masters/${id}/profile-image`,
    method: 'GET',
    responseType: 'blob',
    signal,
  },
);

export const getGetMasterProfileImageQueryKey = (id?: string) => [`/api/v1/masters/${id}/profile-image`] as const;

export const getGetMasterProfileImageQueryOptions = <TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterProfileImageQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterProfileImage>>> = ({ signal }) => getMasterProfileImage(id, signal);

  return {
    queryKey, queryFn, enabled: !!(id), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterProfileImageQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterProfileImage>>>;
export type GetMasterProfileImageQueryError = ProblemDetails;

export function useGetMasterProfileImage<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterProfileImage>>,
  TError,
  Awaited<ReturnType<typeof getMasterProfileImage>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterProfileImage<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterProfileImage>>,
  TError,
  Awaited<ReturnType<typeof getMasterProfileImage>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterProfileImage<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get master profile image
 */

export function useGetMasterProfileImage<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterProfileImageQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMasterProfileImageSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterProfileImageQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterProfileImage>>> = ({ signal }) => getMasterProfileImage(id, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterProfileImageSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterProfileImage>>>;
export type GetMasterProfileImageSuspenseQueryError = ProblemDetails;

export function useGetMasterProfileImageSuspense<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterProfileImageSuspense<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterProfileImageSuspense<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get master profile image
 */

export function useGetMasterProfileImageSuspense<TData = Awaited<ReturnType<typeof getMasterProfileImage>>, TError = ProblemDetails>(
  id: string,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterProfileImage>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterProfileImageSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Upload an image for a master job
 */
export const uploadMasterJobImage = (
  masterId: string,
  jobId: string,
  uploadMasterJobImageBody: UploadMasterJobImageBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append('masterId', uploadMasterJobImageBody.masterId);
  formData.append('masterJobId', uploadMasterJobImageBody.masterJobId);
  uploadMasterJobImageBody.files.forEach((value) => formData.append('files', value));

  return customClient<UploadMasterJobImageResponse>(
    {
      url: `/api/v1/masters/${masterId}/jobs/${jobId}/images`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
  );
};

export const getUploadMasterJobImageMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadMasterJobImage>>, TError, { masterId: string;jobId: string;data: UploadMasterJobImageBody }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof uploadMasterJobImage>>, TError, { masterId: string;jobId: string;data: UploadMasterJobImageBody }, TContext> => {
  const mutationKey = ['uploadMasterJobImage'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadMasterJobImage>>, { masterId: string;jobId: string;data: UploadMasterJobImageBody }> = (props) => {
    const { masterId, jobId, data } = props ?? {};

    return uploadMasterJobImage(masterId, jobId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadMasterJobImageMutationResult = NonNullable<Awaited<ReturnType<typeof uploadMasterJobImage>>>;
export type UploadMasterJobImageMutationBody = UploadMasterJobImageBody;
export type UploadMasterJobImageMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Upload an image for a master job
 */
export const useUploadMasterJobImage = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadMasterJobImage>>, TError, { masterId: string;jobId: string;data: UploadMasterJobImageBody }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof uploadMasterJobImage>>,
  TError,
  { masterId: string;jobId: string;data: UploadMasterJobImageBody },
  TContext
  > => {
  const mutationOptions = getUploadMasterJobImageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get master job image
 */
export const getMasterJobImageById = (
  masterId: string,
  jobId: string,
  imageId: string,
  signal?: AbortSignal,
) => customClient<GetMasterJobImageByIdResponse>(
  { url: `/api/v1/masters/${masterId}/jobs/${jobId}/images/${imageId}`, method: 'GET', signal },
);

export const getGetMasterJobImageByIdQueryKey = (
  masterId?: string,
  jobId?: string,
  imageId?: string,
) => [`/api/v1/masters/${masterId}/jobs/${jobId}/images/${imageId}`] as const;

export const getGetMasterJobImageByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(masterId: string,
  jobId: string,
  imageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterJobImageByIdQueryKey(masterId, jobId, imageId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterJobImageById>>> = ({ signal }) => getMasterJobImageById(masterId, jobId, imageId, signal);

  return {
    queryKey, queryFn, enabled: !!(masterId && jobId && imageId), ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterJobImageByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterJobImageById>>>;
export type GetMasterJobImageByIdQueryError = ProblemDetails;

export function useGetMasterJobImageById<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>> & Pick<
  DefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterJobImageById>>,
  TError,
  Awaited<ReturnType<typeof getMasterJobImageById>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterJobImageById<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>> & Pick<
  UndefinedInitialDataOptions<
  Awaited<ReturnType<typeof getMasterJobImageById>>,
  TError,
  Awaited<ReturnType<typeof getMasterJobImageById>>
  >, 'initialData'
  >, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterJobImageById<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get master job image
 */

export function useGetMasterJobImageById<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string,
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterJobImageByIdQueryOptions(masterId, jobId, imageId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMasterJobImageByIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(masterId: string,
  jobId: string,
  imageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMasterJobImageByIdQueryKey(masterId, jobId, imageId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMasterJobImageById>>> = ({ signal }) => getMasterJobImageById(masterId, jobId, imageId, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMasterJobImageByIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getMasterJobImageById>>>;
export type GetMasterJobImageByIdSuspenseQueryError = ProblemDetails;

export function useGetMasterJobImageByIdSuspense<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterJobImageByIdSuspense<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetMasterJobImageByIdSuspense<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, }
  , queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get master job image
 */

export function useGetMasterJobImageByIdSuspense<TData = Awaited<ReturnType<typeof getMasterJobImageById>>, TError = ProblemDetails>(
  masterId: string,
  jobId: string,
  imageId: string,
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getMasterJobImageById>>, TError, TData>>, },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMasterJobImageByIdSuspenseQueryOptions(masterId, jobId, imageId, options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Delete master job image
 */
export const deleteMasterJobImage = (
  masterId: string,
  jobId: string,
  imageId: string,
) => customClient<void>(
  { url: `/api/v1/masters/${masterId}/jobs/${jobId}/images/${imageId}`, method: 'DELETE' },
);

export const getDeleteMasterJobImageMutationOptions = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMasterJobImage>>, TError, { masterId: string;jobId: string;imageId: string }, TContext>, },
  ): UseMutationOptions<Awaited<ReturnType<typeof deleteMasterJobImage>>, TError, { masterId: string;jobId: string;imageId: string }, TContext> => {
  const mutationKey = ['deleteMasterJobImage'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMasterJobImage>>, { masterId: string;jobId: string;imageId: string }> = (props) => {
    const { masterId, jobId, imageId } = props ?? {};

    return deleteMasterJobImage(masterId, jobId, imageId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMasterJobImageMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMasterJobImage>>>;

export type DeleteMasterJobImageMutationError = ProblemDetails | ProblemDetails | ValidationProblemDetails;

/**
 * @summary Delete master job image
 */
export const useDeleteMasterJobImage = <TError = ProblemDetails | ProblemDetails | ValidationProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMasterJobImage>>, TError, { masterId: string;jobId: string;imageId: string }, TContext>, },
    queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof deleteMasterJobImage>>,
  TError,
  { masterId: string;jobId: string;imageId: string },
  TContext
  > => {
  const mutationOptions = getDeleteMasterJobImageMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
